import {afterEach,describe,it,expect,vi} from 'vitest';
import {cleanup,render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import App from '../App';
afterEach(()=>{cleanup();vi.unstubAllGlobals();localStorage.clear();history.replaceState({},'','/');});
describe('operator console',()=>{
 it('connects with a token and keeps the secret out of persisted preferences',async()=>{let loggedIn=false;const user=userEvent.setup();const fetcher=vi.fn(async(url:string,init?:RequestInit)=>{if(url.endsWith('/v1/auth/login')){expect(JSON.parse(String(init?.body))).toEqual({token:'ore-test-secret'});loggedIn=true;return new Response('{}');}if(!loggedIn)return new Response(JSON.stringify({detail:'Unauthorized'}),{status:401});if(new URL(url).pathname==='/v1/sources')return new Response(JSON.stringify([{id:'crossref',name:'Crossref'}]));return new Response('[]');});vi.stubGlobal('fetch',fetcher);render(<App/>);await user.type(await screen.findByLabelText('Operator token'),'ore-test-secret');await user.click(screen.getByRole('button',{name:'Connect workspace'}));await waitFor(()=>expect(screen.getByRole('heading',{name:'What would you like to collect?'})).toBeInTheDocument());await user.click(screen.getByRole('button',{name:'Missions'}));expect(screen.getByRole('heading',{name:'Missions'})).toBeInTheDocument();expect(Object.values(localStorage)).not.toContain('ore-test-secret');await user.click(screen.getByRole('button',{name:/New mission/}));expect(await screen.findByRole('dialog')).toBeInTheDocument();await waitFor(()=>expect(screen.getByRole('button',{name:'Crossref'})).toBeInTheDocument());});
});

describe('workspace appearance',()=>{
 it('uses original brand assets and persists appearance without changing session secrets',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response('[]')));const user=userEvent.setup();render(<App/>);await screen.findByRole('heading',{name:'What would you like to collect?'});expect(document.querySelector('img[src="/brand/ore-original.svg"]')).not.toBeNull();expect(document.documentElement.dataset.theme).toBe('light');await user.click(screen.getByRole('button',{name:'Switch to dark theme'}));expect(document.documentElement.dataset.theme).toBe('dark');expect(localStorage.getItem('ore.theme')).toBe('dark');await user.click(screen.getByRole('button',{name:'Switch to light theme'}));expect(document.documentElement.dataset.theme).toBe('light');});
});
