import {afterEach, describe, expect, it, vi} from 'vitest';
import {act, cleanup, render, screen, waitFor, within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {OreClient} from '@ore/sdk';
import type {Conversation, ConversationEvent, Model} from '@ore/sdk';
import ChatView, {mergeConversationEvents} from '../components/ChatView';
import {routeFromPath} from '../App';

afterEach(()=>{cleanup();vi.restoreAllMocks();});
const plan={id:'plan-1',revision:1,goal:'Collect the original articles',status:'proposed',scope:{journal:'JACC',month:'June 2024'},outputs:['Main PDF','All supplements'],acceptance:['Official issue inventory reconciled'],workflow:{nodes:[{id:'inventory',kind:'agent',goal:'Read the official archive before metadata lookup'}]}};
const models:Model[]=[{id:'available-model',displayName:'Available model',supportedReasoningEfforts:[{reasoningEffort:'low'},{reasoningEffort:'high'}]}];
function harness(initial:Partial<Conversation>={}){
 let state:Conversation={id:'chat-1',title:'JACC collection',status:'awaiting_user',messages:[{id:'m1',role:'user',content:'Find JACC originals.'}],plans:[],runs:[],questions:[],events:[],events_cursor:0,...initial};
 const streams:ReadableStreamDefaultController<Uint8Array>[]=[];
 const calls:{path:string;init:RequestInit;body:Record<string,unknown>}[]=[];
 const fetcher=vi.fn(async(input:RequestInfo|URL,init:RequestInit={})=>{const path=new URL(String(input)).pathname;const body=init.body?JSON.parse(String(init.body)):{};calls.push({path,init,body});
  if(path.endsWith('/events'))return new Response(new ReadableStream<Uint8Array>({start(controller){streams.push(controller);}}));
  if(path==='/v1/conversations'&&init.method==='POST')return Response.json(state);
  if(path.endsWith('/messages')){state={...state,status:'planning',planner_running:true,messages:[...state.messages,{id:'m2',role:'user',content:String(body.content)}]};return Response.json(state);}
  if(path.endsWith('/approve')){state={...state,status:'running',plans:[{...plan,status:'approved'}],runs:[{id:'run-1',status:'running'}]};return Response.json(state);}
  if(path.endsWith('/interrupt')){state={...state,status:'interrupting',planner_running:false};return Response.json(state);}
  if(path.endsWith('/resume')){state={...state,status:'running',planner_running:false};return Response.json(state);}
  return Response.json(state);
 });
 const client=new OreClient({baseUrl:'http://ore.test',fetch:fetcher});
 return {client,calls,fetcher,setState:(next:Partial<Conversation>)=>{state={...state,...next};},emit:async(event:ConversationEvent)=>{state={...state,events:[...(state.events??[]),event],events_cursor:event.id};await act(async()=>{streams.at(-1)?.enqueue(new TextEncoder().encode(`id: ${event.id}\nevent: ${event.type}\ndata: ${JSON.stringify(event)}\n\n`));});}};
}
function view(client:OreClient,id='chat-1',onNavigate=vi.fn()){return <ChatView client={client} id={id} models={models} onNavigate={onNavigate} onChanged={vi.fn()}/>;}

describe('conversation workspace',()=>{
 it('makes chat the default and preserves durable legacy routes',()=>{expect(routeFromPath('/')).toEqual({view:'chat',id:''});expect(routeFromPath('/chat/chat-1')).toEqual({view:'chat',id:'chat-1'});expect(routeFromPath('/jobs/job-1')).toEqual({view:'missions',id:'job-1'});});
 it('sends a natural-language request without scholarly form requirements or implicit plan approval',async()=>{const h=harness();const user=userEvent.setup();const navigate=vi.fn();render(view(h.client,'',navigate));await user.type(screen.getByLabelText('Message ORE'),'Extract the introduction from https://example.org/report');await user.click(screen.getByRole('button',{name:'Send message'}));await waitFor(()=>expect(h.calls.some(call=>call.path.endsWith('/messages'))).toBe(true));expect(navigate).toHaveBeenCalledWith('/chat/chat-1');const message=h.calls.find(call=>call.path.endsWith('/messages'))!;expect(message.body).toEqual({content:'Extract the introduction from https://example.org/report',mode:'execute',model_policy:'auto'});expect(h.calls.some(call=>call.path.endsWith('/approve'))).toBe(false);});
 it('restores questions and accepts an answer in the same conversation',async()=>{const h=harness({questions:[{id:'q1',question:'Do you need the original files or metadata?',options:[{label:'Original files'},{label:'Metadata'}]}]});const user=userEvent.setup();render(view(h.client));expect(await screen.findByText('Do you need the original files or metadata?')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Original files'}));await user.click(screen.getByRole('button',{name:'Send message'}));await waitFor(()=>expect(h.calls.find(call=>call.path.endsWith('/messages'))?.body.content).toBe('Original files'));});
 it('shows a reviewable plan and starts only on approval',async()=>{const h=harness({plans:[plan],active_plan_id:'plan-1'});const user=userEvent.setup();render(view(h.client));const card=await screen.findByRole('region',{name:'Plan revision 1'});expect(within(card).getByText('All supplements')).toBeInTheDocument();expect(within(card).getByText('Read the official archive before metadata lookup')).toBeInTheDocument();expect(h.calls.some(call=>call.path.endsWith('/approve'))).toBe(false);await user.click(within(card).getByRole('button',{name:'Approve and run'}));await waitFor(()=>expect(h.calls.some(call=>call.path==='/v1/conversations/chat-1/plans/plan-1/approve')).toBe(true));expect(await screen.findByRole('button',{name:'Stop ORE'})).toBeInTheDocument();});
 it('keeps sending enabled during execution and waits for actual stop confirmation before resume',async()=>{const h=harness({status:'running',runs:[{id:'run-1',status:'running'}]});const user=userEvent.setup();render(view(h.client));await user.type(await screen.findByLabelText('Message ORE'),'How far along are you?');await user.click(screen.getByRole('button',{name:'Send message'}));await waitFor(()=>expect(h.calls.find(call=>call.path.endsWith('/messages'))?.body.content).toBe('How far along are you?'));await user.click(screen.getByRole('button',{name:'Stop ORE'}));expect(await screen.findByText('Stopping work. Waiting for workers to confirm.')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Resume'})).not.toBeInTheDocument();h.setState({status:'paused',planner_running:false,runs:[{id:'run-1',status:'paused'}]});await h.emit({id:1,type:'status',data:{status:'paused'}});await user.click(await screen.findByRole('button',{name:'Resume'}));await waitFor(()=>expect(h.calls.some(call=>call.path.endsWith('/resume'))).toBe(true));});
 it('reloads persisted public progress and resumes the stream after its cursor without duplicates',async()=>{const event={id:12,type:'model_selected',data:{model:'available-model',reasoning_effort:'low',summary:'The validated classification task can use less reasoning.'}};const h=harness({events:[event],events_cursor:12});const first=render(view(h.client));await waitFor(()=>expect(h.calls.some(call=>call.path.endsWith('/events'))).toBe(true));expect(h.calls.find(call=>call.path.endsWith('/events'))!.init.headers).toBeInstanceOf(Headers);expect((h.calls.find(call=>call.path.endsWith('/events'))!.init.headers as Headers).get('Last-Event-ID')).toBe('12');expect(await screen.findByText(event.data.summary)).toBeInTheDocument();await h.emit(event);expect(screen.getAllByText(event.data.summary)).toHaveLength(1);first.unmount();render(view(h.client));expect(await screen.findByText(event.data.summary)).toBeInTheDocument();await waitFor(()=>expect(h.calls.filter(call=>call.path.endsWith('/events'))).toHaveLength(2));});
 it('displays send failures and preserves the unsent draft',async()=>{const client=new OreClient({baseUrl:'http://ore.test',fetch:async(input)=>String(input).endsWith('/messages')?Response.json({detail:'Planner backend is unavailable'},{status:503}):Response.json({id:'chat-1',title:'New conversation',status:'draft',messages:[],plans:[],runs:[],events:[]})});const user=userEvent.setup();render(view(client,''));await user.type(screen.getByLabelText('Message ORE'),'Collect the public report');await user.click(screen.getByRole('button',{name:'Send message'}));expect(await screen.findByRole('alert')).toHaveTextContent('Planner backend is unavailable');expect(screen.getByLabelText('Message ORE')).toHaveValue('Collect the public report');});
 it('uses only runtime-advertised fixed model reasoning choices',async()=>{const h=harness();const user=userEvent.setup();render(view(h.client,''));await user.selectOptions(screen.getByLabelText('Model policy'),'fixed');expect(within(screen.getByLabelText('Reasoning effort')).getAllByRole('option').map(option=>option.getAttribute('value'))).toEqual(['low','high']);await user.selectOptions(screen.getByLabelText('Reasoning effort'),'high');await user.type(screen.getByLabelText('Message ORE'),'Collect the report');await user.click(screen.getByRole('button',{name:'Send message'}));await waitFor(()=>expect(h.calls.find(call=>call.path.endsWith('/messages'))?.body).toMatchObject({model_policy:'fixed',model:'available-model',reasoning_effort:'high'}));});
 it('requires an explicit continuation choice for an approved running plan',async()=>{const h=harness({status:'running',approved_plan_id:'plan-1',plans:[{...plan,status:'approved'}]});const user=userEvent.setup();render(view(h.client));await screen.findByRole('heading',{name:'JACC collection'});await user.selectOptions(screen.getByLabelText('Conversation mode'),'execute');await user.click(screen.getByRole('checkbox',{name:'Apply changes and continue'}));await user.type(screen.getByLabelText('Message ORE'),'Include the July issues too');await user.click(screen.getByRole('button',{name:'Send message'}));await waitFor(()=>expect(h.calls.find(call=>call.path.endsWith('/messages'))?.body).toMatchObject({mode:'execute',change_and_continue:true}));});
 it('allows explicit approval of a paused proposed plan without a resume deadlock',async()=>{const h=harness({status:'paused',plans:[plan],active_plan_id:'plan-1'});render(view(h.client));expect(await screen.findByRole('button',{name:'Approve and run'})).toBeEnabled();expect(screen.queryByRole('button',{name:'Resume'})).not.toBeInTheDocument();});
 it('renders public model routing summaries from bridged workflow events',async()=>{const h=harness({events:[{id:3,type:'progress',data:{phase:'execution',event_type:'model_selected',model:'available-model',routing_reason:'Validated classification can use low effort.'}}],events_cursor:3});render(view(h.client));expect(await screen.findByText('Model Selected')).toBeInTheDocument();expect(screen.getByText('Validated classification can use low effort.')).toBeInTheDocument();});
 it('deduplicates public event IDs while retaining new details',()=>{expect(mergeConversationEvents([{id:2,type:'progress',data:'old'}],[{id:2,type:'progress',data:'updated'},{id:3,type:'status',data:'paused'}])).toEqual([{id:2,type:'progress',data:'updated'},{id:3,type:'status',data:'paused'}]);});
});

// Public streaming is replayed from persisted events, never simulated locally.
describe('public response streaming and collection scope',()=>{
 it('renders genuine response deltas, deduplicates replay, and restores interrupted text',async()=>{const h=harness({status:'planning',planner_running:true});render(view(h.client));await waitFor(()=>expect(h.calls.some(call=>call.path.endsWith('/events'))).toBe(true));await h.emit({id:1,type:'message.delta',data:{message_id:'answer-1',operator_message_id:'m1',sequence:1,delta:'The official ',status:'streaming'}});expect(screen.getByText('The official')).toBeInTheDocument();await h.emit({id:2,type:'message.delta',data:{message_id:'answer-1',operator_message_id:'m1',sequence:2,delta:'inventory is open.',status:'streaming'}});expect(screen.getByText('The official inventory is open.')).toBeInTheDocument();await h.emit({id:2,type:'message.delta',data:{message_id:'answer-1',operator_message_id:'m1',sequence:2,delta:'inventory is open.',status:'streaming'}});expect(screen.getAllByText('The official inventory is open.')).toHaveLength(1);await h.emit({id:3,type:'message.complete',data:{message_id:'answer-1',operator_message_id:'m1',sequence:3,content:'The official inventory is open.',status:'interrupted'}});expect(screen.getByText('Response interrupted · received text saved')).toBeInTheDocument();expect(screen.queryByText('Receiving response…')).not.toBeInTheDocument();});
 it('keeps plans and model routing decisions attached to their original turn',async()=>{const h=harness({messages:[{id:'m1',role:'user',content:'Collect the June issue'},{id:'a1',role:'assistant',content:'June plan ready',operator_message_id:'m1',plan_id:'plan-1'},{id:'m2',role:'user',content:'Now describe the limitations'}],plans:[{...plan,status:'approved',operator_message_id:'m1'}],events:[{id:4,type:'progress',operator_message_id:'m1',data:{event_type:'model_selected',summary:'model selected',routing_reason:'Validated steps now run without a model.'}}],events_cursor:4});render(view(h.client));const first=await screen.findByRole('region',{name:'Conversation turn 1'});expect(within(first).getByRole('region',{name:'Plan revision 1'})).toBeInTheDocument();expect(within(first).getByText('Validated steps now run without a model.')).toBeInTheDocument();expect(within(screen.getByRole('region',{name:'Conversation turn 2'})).queryByText('June plan ready')).not.toBeInTheDocument();});
 it('shows collection completeness separately from a completed node graph',async()=>{const h=harness({status:'finished_incomplete',runs:[{id:'r1',status:'finished_incomplete',nodes:[{id:'n1',status:'succeeded'}],collection_progress:{denominator:{status:'provisional',total:null,basis:'Official issue enumeration is incomplete.'},resources:{discovered:19,included:12,complete:8,unresolved:4},roles:[{role:'main_pdf',expected:12,verified:8,missing:4,unknown:0},{role:'supplement',expected:null,verified:5,missing:0,unknown:4}],issues:{discovered:2,complete:1,total:null},gaps:{count:4,by_kind:{article_manifest_missing:4}}}}]});render(view(h.client));expect(await screen.findByText('Official issue enumeration is incomplete.')).toBeInTheDocument();expect(screen.getByText('1 of 1 known tasks complete.',{exact:false})).toBeInTheDocument();expect(screen.queryByRole('progressbar')).not.toBeInTheDocument();expect(screen.getByText('5 verified · requirement count open')).toBeInTheDocument();expect(screen.queryByText('All declared requirements in this scope are verified.')).not.toBeInTheDocument();});
 it('renders safe Markdown without loading remote images or injecting HTML',async()=>{const h=harness({messages:[{id:'m1',role:'user',content:'Explain'},{id:'a1',role:'assistant',content:'**Verified** [source](https://example.org/paper) ![remote image](https://tracking.invalid/image.png) <script>alert(1)</script>',operator_message_id:'m1'}]});render(view(h.client));expect(await screen.findByText('Verified')).toHaveProperty('tagName','STRONG');expect(screen.getByRole('link',{name:'source'})).toHaveAttribute('rel','noopener noreferrer');expect(document.querySelector('img[src^="https://tracking"]')).toBeNull();expect(document.querySelector('script')).toBeNull();});
});

describe('execution capacity',()=>{
 it('keeps requested, ready and running counts separate without claiming native Chrome readiness',async()=>{const state={id:'chat-1',title:'Parallel collection',status:'running',messages:[{id:'m1',role:'user',content:'Collect these pages'}],plans:[],runs:[{id:'run-1',job_id:'job-1',status:'running',operator_message_id:'m1'}],events:[],events_cursor:0};const client=new OreClient({baseUrl:'http://ore.test',fetch:async(input)=>{const path=new URL(String(input)).pathname;if(path.endsWith('/events'))return new Response(new ReadableStream());if(path==='/v1/scheduler')return Response.json({global:{desired_executors:6,ready_executors:3,global_limit:8},jobs:[{job_id:'job-1',running:2,target:4,approved_max:5,reason:'Scaling within the approved cap.'}]});if(path.includes('/artifacts')||path.includes('/handoffs'))return Response.json([]);return Response.json(state);}});render(view(client));expect(await screen.findByText('Pool requested')).toBeInTheDocument();const capacity=screen.getByText('Pool requested').closest('details')!;expect(within(capacity).getByText('6')).toBeInTheDocument();expect(within(capacity).getByText('3')).toBeInTheDocument();expect(within(capacity).getByText('2')).toBeInTheDocument();expect(within(capacity).queryByText(/Native Chrome ready/)).not.toBeInTheDocument();});
});

describe('generic content outputs',()=>{
 it('shows verified output counts without inventing a scholarly inventory',async()=>{const h=harness({status:'completed',runs:[{id:'r1',status:'completed',collection_progress:{kind:'artifacts',artifacts:{known:1,verified:1},denominator:{status:'unknown',basis:'No registered resource inventory',total:null},resources:{discovered:0,included:0,complete:0,unresolved:0},roles:[],issues:{discovered:0,complete:0,total:null},gaps:{count:0,by_kind:{}}}}]});render(view(h.client));expect(await screen.findByRole('region',{name:'Output verification'})).toBeInTheDocument();expect(screen.queryByText('Discovering scope')).not.toBeInTheDocument();expect(screen.queryByRole('progressbar')).not.toBeInTheDocument();});
});

describe('runtime and shared budget evidence',()=>{
 it('shows actual runtime, shared remaining limits and recipe candidates separately',async()=>{
  const h=harness({status:'running',runs:[{id:'r1',status:'running',execution_runtime:'native',runtime_details:{model:'available-model',effort:'high',adaptation_status:'awaiting_native_outcome_validation'},usage:{tokens:{totalTokens:12400},provider_turns:3,elapsed_seconds:12,remaining_seconds:168,remaining_tokens:37600,usage_complete:true,zero_model_calls:false,token_overshoot:0,paused:false},reuse:{verified_reuses:2,candidate_recipes:4,promoted_recipes:1},validation_strength:{schema:true,receipt:true,independent_goal:false,corpus:false}}]});
  render(view(h.client));const panel=await screen.findByLabelText('Execution and budget');
  expect(within(panel).getByText('available-model · high')).toBeInTheDocument();
  expect(within(panel).getByText('2m 48s')).toBeInTheDocument();expect(within(panel).getByText('37,600')).toBeInTheDocument();
  expect(within(panel).getByText('Verified recipe reuses')).toBeInTheDocument();expect(within(panel).getByText('Recipe candidates')).toBeInTheDocument();
  expect(within(panel).getByText('Recipe candidates still need validation before automatic reuse.')).toBeInTheDocument();
  expect(within(panel).getByText('Quality baseline · cheaper routes are not yet validated.')).toBeInTheDocument();
  expect(within(panel).getByText('Output shape checks do not establish collection completeness.')).toBeInTheDocument();
  expect(within(panel).queryByText('No model calls in this budget scope.')).not.toBeInTheDocument();
 });
 it('retains zero remaining, overshoot and incomplete usage without claiming no model calls',async()=>{
  const h=harness({status:'paused_budget',runs:[{id:'r1',status:'paused_budget',execution_runtime:'structured',usage:{tokens:{totalTokens:501200},remaining_seconds:0,remaining_tokens:0,provider_turns:8,usage_complete:false,zero_model_calls:true,token_overshoot:1200,paused:true}}]});
  render(view(h.client));const panel=await screen.findByLabelText('Execution and budget');
  expect(within(panel).getByText('501,200 · partial')).toBeInTheDocument();expect(within(panel).getByText('1,200')).toBeInTheDocument();expect(within(panel).getByText('0s')).toBeInTheDocument();
  expect(within(panel).getByRole('status')).toHaveTextContent('Usage is incomplete.');expect(within(panel).getByText('Budget clock paused.')).toBeInTheDocument();
  expect(within(panel).queryByText('No model calls in this budget scope.')).not.toBeInTheDocument();
 });
 it('shows planning budget before a workflow exists and does not turn unlimited limits into zero',async()=>{
  const h=harness({status:'planning',planner_running:true,usage:{tokens:{totalTokens:0},provider_turns:0,elapsed_seconds:0,remaining_seconds:null,remaining_tokens:null,usage_complete:true,zero_model_calls:true,paused:false}});
  render(view(h.client));const panel=await screen.findByLabelText('Request budget');
  expect(within(panel).getAllByText('Not limited')).toHaveLength(2);expect(within(panel).getByText('No model calls in this budget scope.')).toBeInTheDocument();
  expect(within(panel).queryByText('Native agent')).not.toBeInTheDocument();
 });
 it('keeps historical workflows without runtime telemetry unchanged',async()=>{
  const h=harness({status:'completed',runs:[{id:'old-run',status:'completed'}]});render(view(h.client));
  await screen.findByText('Execution completed.');expect(screen.queryByLabelText('Execution and budget')).not.toBeInTheDocument();expect(screen.queryByText('Observed tokens')).not.toBeInTheDocument();
 });
});

describe('subscription and API account selection',()=>{
 it('uses explicit Claude aliases and keeps Plan an available choice',async()=>{const h=harness();const user=userEvent.setup();render(view(h.client,''));expect(screen.getByLabelText('Conversation mode')).toHaveValue('execute');await user.selectOptions(screen.getByLabelText('Agent account'),'claude_code');await user.selectOptions(screen.getByLabelText('Claude model'),'opus');await user.selectOptions(screen.getByLabelText('Conversation mode'),'plan');await user.type(screen.getByLabelText('Message ORE'),'Plan a collection');await user.click(screen.getByRole('button',{name:'Send message'}));await waitFor(()=>expect(h.calls.find(call=>call.path.endsWith('/messages'))?.body).toMatchObject({mode:'plan',model_policy:'fixed',model:'opus',backend:{kind:'claude_code',model:'opus'}}));});
 it('sends only a protected API key reference with an explicit API model',async()=>{const calls:{path:string;body:Record<string,unknown>}[]=[];const state={id:'api-chat',title:'API collection',status:'draft',messages:[],plans:[],runs:[]};const client=new OreClient({baseUrl:'https://ore.test',fetch:async(input,init={})=>{const path=new URL(String(input)).pathname;const body=init.body?JSON.parse(String(init.body)):{};calls.push({path,body});if(path==='/v1/connections')return Response.json({connections:[{id:'api-1',provider:'openai',kind:'model',operation:'model',status:'ready',state_version:2,actions:[],credential_fields:[],configured_fields:['api_key'],backend:{kind:'openai',api_key_ref:'provider/openai/api-1'}}]});if(path==='/v1/providers/status')return Response.json({providers:[]});return Response.json(state);}});const user=userEvent.setup();render(view(client,''));await user.selectOptions(screen.getByLabelText('Agent account'),'openai');await user.type(screen.getByLabelText('Message ORE'),'Collect the report');expect(screen.getByRole('button',{name:'Send message'})).toBeDisabled();await user.type(screen.getByLabelText('Provider model ID'),'my-approved-model');await waitFor(()=>expect(screen.getByRole('button',{name:'Send message'})).toBeEnabled());await user.click(screen.getByRole('button',{name:'Send message'}));await waitFor(()=>expect(calls.find(call=>call.path.endsWith('/messages'))?.body).toMatchObject({model:'my-approved-model',backend:{kind:'openai',model:'my-approved-model',api_key_ref:'provider/openai/api-1'}}));expect(JSON.stringify(calls)).not.toContain('plaintext-key');});
});

it('shows a failed planner field and the recovery action from persisted public events',async()=>{const h=harness();render(view(h.client));await waitFor(()=>expect(h.calls.some(call=>call.path.endsWith('/events'))).toBe(true));await h.emit({id:9,type:'error',data:{code:'planner_timeout',message:'Planning reached its time limit.',last_validation:{fields:[{path:['budget','max_tokens'],message:'A positive integer is required.'}]},action:'Resume planning or correct the indicated field.'}});expect(await screen.findByRole('alert')).toHaveTextContent('budget.max_tokens: A positive integer is required.');expect(screen.getByRole('alert')).toHaveTextContent('Resume planning or correct the indicated field.');});

it('shows source quota retry time instead of an active completion ETA while retrieval waits',async()=>{const h=harness({status:'running',runs:[{id:'waiting-run',status:'running',eta:{remaining_active_seconds:{low:60,high:120}},nodes:[{id:'fetch',status:'retry_wait',retry_at:'2026-09-12T12:00:00Z',error:{code:'source_quota_wait',source:'scopus',operation:'search'}}]}]});render(view(h.client));expect(await screen.findByText('Collection is waiting for a source quota reset. Completion time will be updated when retrieval resumes.',{exact:false})).toBeInTheDocument();expect(screen.getByText(/Scopus · Search is waiting. Next check:/)).toBeInTheDocument();expect(screen.queryByText('1–2 min remaining',{exact:false})).not.toBeInTheDocument();});
