import {afterEach,describe,expect,it,vi} from 'vitest';
import {act,cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {OreClient} from '@ore/sdk';
import type {ConnectionCard} from '@ore/sdk';
import {ConnectionCards,ProviderAccounts} from '../components/ConnectionCards';

afterEach(()=>{cleanup();vi.useRealTimers();localStorage.clear();});
const initial:ConnectionCard={id:'connection-1',provider:'scopus',kind:'source',conversation_id:'c1',operation:'search',status:'awaiting_auth',state_version:1,actions:['mark_pending','refresh'],credential_fields:['api_key'],configured_fields:[]};
function setup(card:ConnectionCard=initial){let state={...card};let offline=false;const calls:{path:string;body:Record<string,unknown>}[]=[];const client=new OreClient({baseUrl:'https://ore.test',fetch:async(input,init={})=>{const url=new URL(String(input));const body=init.body?JSON.parse(String(init.body)):{};calls.push({path:url.pathname,body});if(url.pathname==='/v1/connections'){if(offline)throw new Error('connection unavailable');return Response.json({connections:[state]});}if(url.pathname.endsWith('/secret')){expect(body.expected_version).toBe(state.state_version);state={...state,state_version:state.state_version+1,configured_fields:['api_key']};return Response.json(state);}if(url.pathname.endsWith('/actions')){expect(body.expected_version).toBe(state.state_version);state={...state,state_version:state.state_version+1,status:body.action==='mark_pending'?'pending':body.action==='start_login'?'awaiting_auth':state.status,...(body.action==='start_login'?{verification_url:'https://auth.openai.com/codex/device',user_code:'ABCD-EFGH'}:{})};return Response.json(state);}if(url.pathname==='/v1/providers/status')return Response.json({providers:[{provider:'codex',auth:{status:'ready',plan_type:'Pro'},quota:{status:'unknown',windows:[],ordinary_usage_allowed:null,stale:false}}]});return Response.json([]);}});return {client,calls,setState:(next:Partial<ConnectionCard>)=>{state={...state,...next};},setOffline:(next:boolean)=>{offline=next;}};}
function view(client:OreClient){return <ConnectionCards client={client} conversationId="c1" open={false} onClose={()=>{}} onNavigate={()=>{}}/>;}

describe('persistent in-chat connection actions',()=>{
 it('stores a credential only through the protected endpoint and restores pending status after remount',async()=>{const h=setup();const user=userEvent.setup();const mounted=render(view(h.client));const card=await screen.findByRole('article',{name:'Scopus connection'});await user.click(within(card).getByText('Enter a credential securely'));await user.type(within(card).getByLabelText('Scopus Api Key'),'test-secret-value');await user.click(within(card).getByRole('button',{name:'Save credential'}));await waitFor(()=>expect(h.calls.some(call=>call.path.endsWith('/secret'))).toBe(true));expect(screen.getByLabelText('Scopus Api Key')).toHaveValue('');expect(document.body.textContent).not.toContain('test-secret-value');expect(JSON.stringify(localStorage)).not.toContain('test-secret-value');await user.click(screen.getByRole('button',{name:'Mark approval pending'}));expect(await screen.findByText('Approval is pending. This connection is not ready for collection.')).toBeInTheDocument();mounted.unmount();render(view(h.client));expect(await screen.findByText('Approval is pending. This connection is not ready for collection.')).toBeInTheDocument();expect(h.calls.filter(call=>call.path.endsWith('/secret'))).toHaveLength(1);expect(h.calls.some(call=>call.path.includes('/messages'))).toBe(false);});
 it('starts official model login and exposes only the provider URL and one-time code',async()=>{const h=setup({...initial,provider:'codex',kind:'model',credential_fields:[],actions:['start_login']});const user=userEvent.setup();render(view(h.client));await user.click(await screen.findByRole('button',{name:'Sign in with provider'}));expect(await screen.findByRole('link',{name:'Continue on Codex'})).toHaveAttribute('href','https://auth.openai.com/codex/device');expect(screen.getByText('ABCD-EFGH')).toBeInTheDocument();expect(screen.queryByText('Enter a credential securely')).not.toBeInTheDocument();expect(h.calls.find(call=>call.path.endsWith('/actions'))?.body).toMatchObject({action:'start_login',expected_version:1});});
 it('preserves last state when disconnected and reconciles the next server state without replaying actions',async()=>{vi.useFakeTimers();const h=setup();render(view(h.client));await act(async()=>{await Promise.resolve();});expect(screen.getByRole('article',{name:'Scopus connection'})).toBeInTheDocument();h.setOffline(true);await act(async()=>{await vi.advanceTimersByTimeAsync(5000);});expect(screen.getByRole('status')).toHaveTextContent('Connection updates paused');expect(screen.getByText('Awaiting Auth')).toBeInTheDocument();h.setOffline(false);h.setState({state_version:3,status:'ready',credential_fields:[],message:'API operation verified.'});await act(async()=>{await vi.advanceTimersByTimeAsync(5000);});expect(screen.getByText('API operation verified.')).toBeInTheDocument();expect(screen.queryByText(/Connection updates paused/)).not.toBeInTheDocument();expect(h.calls.filter(call=>call.path.endsWith('/actions'))).toHaveLength(0);});
 it('keeps unavailable account quota distinct from a zero allowance or request budget',async()=>{const h=setup();render(view(h.client));await screen.findByText('Model accounts and API quota');fireEvent.click(screen.getByText('Model accounts and API quota'));const quota=screen.getByRole('region',{name:'Codex account quota'});expect(within(quota).getByText('Quota is not available yet.')).toBeInTheDocument();expect(within(quota).queryByText('0% remaining')).not.toBeInTheDocument();expect(screen.getByText('Provider allowance is separate from this request’s time and token budgets.')).toBeInTheDocument();});
});

it('submits the official Claude authorization code without retaining it in visible state',async()=>{const calls:Record<string,unknown>[]=[];const card={...initial,provider:'claude',kind:'model',credential_fields:[],actions:[],login_code_required:true,verification_url:'https://claude.ai/oauth/authorize'};const client=new OreClient({baseUrl:'https://ore.test',fetch:async(input,init={})=>{if(String(input).includes('/login-code')){calls.push(JSON.parse(String(init.body)));return Response.json({...card,login_code_required:false,status:'ready',state_version:2});}if(String(input).includes('/connections'))return Response.json({connections:[card]});return Response.json({providers:[]});}});const user=userEvent.setup();render(view(client));await user.type(await screen.findByLabelText('Claude Code authorization code'),'temporary-auth-code');await user.click(screen.getByRole('button',{name:'Complete official login'}));await waitFor(()=>expect(calls).toHaveLength(1));expect(calls[0]).toMatchObject({code:'temporary-auth-code',expected_version:1});expect(document.body.textContent).not.toContain('temporary-auth-code');expect(screen.queryByLabelText('Claude Code authorization code')).not.toBeInTheDocument();});

it('renders API quota exhaustion and incomplete source configuration without inventing remaining usage',()=>{
 render(<ProviderAccounts providers={[]} sourceQuotas={[{source:'scopus',credential_id:'key1',quota_group:'shared',status:'quota_exhausted',remaining:0,limit:100,resets_at:1800000000,observed_at:1799999900,access_profile_ref:'institution'},{status:'invalid_configuration',access_profile_ref:'broken'}]} onRefresh={()=>{}}/>);
 expect(screen.getByText('0 requests remaining / 100')).toBeInTheDocument();expect(screen.getByText('Remaining requests unknown')).toBeInTheDocument();expect(screen.getByText('Invalid Configuration')).toBeInTheDocument();expect(screen.getByText(/^Resets /)).not.toHaveTextContent('—');
});

it.each([['https://auth0.openai.com/codex/device',true],['https://auth0.openai.com.attacker.invalid/codex/device',false]])('limits Codex login host matching for %s',async(url,allowed)=>{
 const h=setup({...initial,provider:'codex',kind:'model',credential_fields:[],actions:[],verification_url:url});render(view(h.client));await screen.findByRole('article',{name:'Codex connection'});const link=screen.queryByRole('link',{name:'Continue on Codex'});if(allowed)expect(link).toHaveAttribute('href',url);else expect(link).not.toBeInTheDocument();
});

it('renders the official Claude login expiry supplied as epoch seconds',async()=>{
 const h=setup({...initial,provider:'claude_code',kind:'model',credential_fields:[],actions:[],verification_url:'https://claude.ai/oauth/authorize',expires_at:1800000000});render(view(h.client));await screen.findByRole('article',{name:'Claude Code connection'});const expiry=screen.getByText(/^Expires /);expect(expiry).not.toHaveTextContent('—');expect(expiry).toHaveTextContent(new Date(1800000000*1000).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}));
});


it.each([['crossref','email','contact@example.test'],['scienceon','client_id','test-client'],['scienceon','token','test-token'],['scopus','insttoken','test-institution-token']])('accepts the registry-declared %s %s field through protected entry',async(provider,field,value)=>{
 const h=setup({...initial,provider,credential_fields:[field],actions:[]});const user=userEvent.setup();render(view(h.client));
 await user.click(await screen.findByText('Enter a credential securely'));const input=screen.getByRole('article',{name:new RegExp('connection$')}).querySelector('input')!;await user.type(input,value);await user.click(screen.getByRole('button',{name:'Save credential'}));
 await waitFor(()=>expect(h.calls.find(call=>call.path.endsWith('/secret'))?.body).toMatchObject({field,value}));expect(input).toHaveValue('');expect(document.body.textContent).not.toContain(value);expect(JSON.stringify(localStorage)).not.toContain(value);
});


it('saves a named source key through the protected endpoint without claiming extra quota',async()=>{
 const h=setup({...initial,credential_pool_allowed:true,credential_pool:[{id:'primary',enabled:true}]});const user=userEvent.setup();render(view(h.client));await user.click(await screen.findByText('Enter a credential securely'));
 const keyLabel=screen.getByLabelText('Key label for Scopus');expect(keyLabel).toHaveValue('primary');await user.clear(keyLabel);await user.type(keyLabel,'licensed-secondary');await user.type(screen.getByLabelText('Scopus Api Key'),'private-source-key');await user.click(screen.getByRole('button',{name:'Save credential'}));
 await waitFor(()=>expect(h.calls.find(call=>call.path.endsWith('/secret'))?.body).toMatchObject({field:'api_key',value:'private-source-key',credential_id:'licensed-secondary'}));
 expect(screen.getByText('Choose a label to add or replace a saved key. Keys share the provider’s allowance; adding keys does not increase that allowance.')).toBeInTheDocument();expect(document.body.textContent).not.toContain('private-source-key');expect(keyLabel).toHaveValue('licensed-secondary');
});

it('does not offer multiple PubMed keys even if an older server advertises a pool',async()=>{
 const h=setup({...initial,provider:'pubmed',credential_pool_allowed:true});render(view(h.client));await screen.findByRole('article',{name:'Pubmed connection'});expect(screen.queryByLabelText('Key label for Pubmed')).not.toBeInTheDocument();
});


it('verifies a configured source API from its chat card using a versioned action',async()=>{
 const h=setup({...initial,status:'needs_verification',actions:['verify'],configured_fields:['api_key'],message_code:'setup_complete_verify_connection'});const user=userEvent.setup();render(view(h.client));
 expect(await screen.findByText('Setup is complete. Verify the API to check whether collection is available.')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Verify API'}));
 await waitFor(()=>expect(h.calls.find(call=>call.path.endsWith('/actions'))?.body).toMatchObject({action:'verify',expected_version:1,idempotency_key:expect.any(String)}));expect(h.calls.some(call=>call.path.includes('/messages')||call.path.endsWith('/secret'))).toBe(false);
});
