import {useState} from 'react';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {cleanup,render,screen,waitFor,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {OreClient} from '@ore/sdk';
import type {ConversationFolder,ConversationSummary} from '@ore/sdk';
import ConversationLibrary from '../components/ConversationLibrary';
import ChatView from '../components/ChatView';
afterEach(cleanup);

describe('purpose folders and conversation branches',()=>{
 it('creates, renames and removes a folder while preserving its conversation',async()=>{let folders:ConversationFolder[]=[];let conversations:ConversationSummary[]=[{id:'c1',title:'June original articles',status:'completed'}];const calls:string[]=[];const client=new OreClient({baseUrl:'https://ore.test',fetch:async(input,init={})=>{const path=new URL(String(input)).pathname;calls.push((init.method??'GET')+' '+path);const body=init.body?JSON.parse(String(init.body)):{};if(path==='/v1/conversation-folders'&&init.method==='POST'){const folder={id:'folder-1',title:body.title};folders=[folder];return Response.json(folder);}if(path==='/v1/conversation-folders')return Response.json({folders});if(path==='/v1/conversation-folders/folder-1'&&init.method==='PATCH'){folders=[{...folders[0],title:body.title}];return Response.json(folders[0]);}if(init.method==='DELETE'){folders=[];conversations=conversations.map(item=>({...item,folder_id:null}));return new Response(null,{status:204});}if(path==='/v1/conversations/c1'&&init.method==='PATCH'){conversations=conversations.map(item=>({...item,...body}));return Response.json(conversations[0]);}return Response.json([]);}});function Wrapper(){const [items,setItems]=useState(conversations);return <ConversationLibrary client={client} conversations={items} search="" selected="" onNavigate={()=>{}} onChanged={()=>setItems([...conversations])}/>;}const user=userEvent.setup();render(<Wrapper/>);await user.click(screen.getByRole('button',{name:'Create purpose folder'}));await user.type(screen.getByLabelText('New purpose folder'),'Cardiology');await user.click(screen.getByRole('button',{name:'Save folder'}));await user.click(await screen.findByLabelText('Manage conversation June original articles'));await user.selectOptions(screen.getByLabelText('Folder for June original articles'),'folder-1');await waitFor(()=>expect(conversations[0].folder_id).toBe('folder-1'));await user.click(screen.getByRole('button',{name:'Rename folder Cardiology'}));await user.clear(screen.getByLabelText('Rename folder'));await user.type(screen.getByLabelText('Rename folder'),'Review');await user.click(screen.getByRole('button',{name:'Save folder'}));await user.click(await screen.findByRole('button',{name:'Remove folder Review'}));await waitFor(()=>expect(conversations[0].folder_id).toBeNull());expect(screen.getByRole('button',{name:'June original articles'})).toBeInTheDocument();expect(calls).toContain('DELETE /v1/conversation-folders/folder-1');expect(calls.some(call=>call.startsWith('DELETE /v1/conversations/'))).toBe(false);});
 it('branches from the selected message and navigates only after the server snapshot exists',async()=>{const navigate=vi.fn();const calls:{path:string;body:unknown}[]=[];const state={id:'c1',title:'Review',status:'completed',messages:[{id:'m1',role:'user',content:'Collect June articles'},{id:'a1',role:'assistant',content:'June scope complete',operator_message_id:'m1'}],plans:[],runs:[],events:[]};const client=new OreClient({baseUrl:'https://ore.test',fetch:async(input,init={})=>{const path=new URL(String(input)).pathname;calls.push({path,body:init.body?JSON.parse(String(init.body)):null});if(path.endsWith('/events'))return new Response(new ReadableStream());if(path.endsWith('/branch'))return Response.json({...state,id:'c2',branched_from:{conversation_id:'c1',message_id:'a1'}});if(path==='/v1/conversations/c1')return Response.json(state);return Response.json([]);}});const user=userEvent.setup();render(<ChatView client={client} id="c1" models={[]} onNavigate={navigate} onChanged={()=>{}}/>);await user.click(await screen.findByRole('button',{name:'Branch from message a1'}));await waitFor(()=>expect(navigate).toHaveBeenCalledWith('/chat/c2'));expect(calls.find(call=>call.path.endsWith('/branch'))?.body).toEqual({message_id:'a1'});expect(state.messages).toHaveLength(2);expect(calls.some(call=>call.path.endsWith('/messages'))).toBe(false);});
});


it('shows nested branches within purpose folders and keeps a filtered child accessible',async()=>{
 const conversations:ConversationSummary[]=[{id:'child',title:'June full text',status:'completed',folder_id:'review',branched_from:{conversation_id:'root',message_id:'m1'}},{id:'grandchild',title:'June supplements',status:'paused',folder_id:'review',branched_from:{conversation_id:'child',message_id:'m2'}},{id:'root',title:'Cardiology overview',status:'completed',folder_id:'review'}];
 const client=new OreClient({baseUrl:'https://ore.test',fetch:async()=>Response.json({folders:[{id:'review',title:'Review'}]})});const navigate=vi.fn();const props={client,conversations,selected:'grandchild',search:'',onNavigate:navigate,onChanged:()=>{}};
 const mounted=render(<ConversationLibrary {...props}/>);await screen.findByRole('button',{name:'Rename folder Review'});
 const branch=await screen.findByRole('list',{name:'Branches of Cardiology overview'});
 expect(within(branch).getByRole('button',{name:'June full text'})).toBeInTheDocument();
 expect(within(branch).getByRole('list',{name:'Branches of June full text'})).toContainElement(screen.getByRole('button',{name:'June supplements'}));
 expect(screen.getAllByRole('button',{name:'June supplements'})).toHaveLength(1);
 mounted.rerender(<ConversationLibrary {...props} search="supplements"/>);
 expect(screen.getByRole('button',{name:'June supplements'})).toBeInTheDocument();expect(screen.queryByRole('list',{name:'Branches of June full text'})).not.toBeInTheDocument();
 const user=userEvent.setup();await user.click(screen.getByLabelText('Manage conversation June supplements'));await user.click(screen.getByRole('button',{name:'Open parent: June full text'}));expect(navigate).toHaveBeenCalledWith('/chat/child');
});
