import {describe,it,expect} from 'vitest';
import type {Conversation} from '@ore/sdk';
import {applyPublicMessageEvent,conversationTurns} from '../lib/conversation';
const snapshot:Conversation={id:'c',title:'Request',status:'planning',messages:[{id:'u',role:'user',content:'Collect'}],plans:[],runs:[],events_cursor:0};
describe('conversation replay',()=>{
 it('waits for a snapshot after a missing delta rather than inventing missing text',()=>{const first=applyPublicMessageEvent(snapshot,{id:1,type:'message.delta',data:{message_id:'m',sequence:1,delta:'First ',operator_message_id:'u'}})!;const skipped=applyPublicMessageEvent(first,{id:3,type:'message.delta',data:{message_id:'m',sequence:3,delta:'last'}})!;expect(skipped.messages.at(-1)?.content).toBe('First ');const complete=applyPublicMessageEvent(skipped,{id:4,type:'message.complete',data:{message_id:'m',sequence:4,content:'First middle last',status:'complete'}})!;expect(complete.messages.at(-1)?.content).toBe('First middle last');});
 it('continues a partially streamed snapshot without duplicate prefix',()=>{const saved:Conversation={...snapshot,messages:[...snapshot.messages,{id:'m',role:'assistant',content:'Saved prefix',status:'streaming',sequence:3,operator_message_id:'u'}],events_cursor:3};const next=applyPublicMessageEvent(saved,{id:4,type:'message.delta',data:{message_id:'m',sequence:4,delta:' and continuation'}})!;expect(next.messages.at(-1)?.content).toBe('Saved prefix and continuation');expect(applyPublicMessageEvent(next,{id:4,type:'message.delta',data:{message_id:'m',sequence:4,delta:' and continuation'}})).toBe(next);});
 it('keeps uncorrelated legacy activity separate from later requests',()=>{const result=conversationTurns({...snapshot,messages:[...snapshot.messages,{id:'u2',role:'user',content:'Second request'}]},[{id:1,type:'progress',data:{summary:'Historical work'}}]);expect(result[0]?.legacy).toBe(true);expect(result[0]?.events).toHaveLength(1);expect(result[2]?.events).toHaveLength(0);});
});
