import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowRight, BookOpen, ChevronRight, Compass, Cpu, Database, Globe2, KeyRound, Layers3, Link2, LogOut, MessageCircle, Moon, Sun, ChevronDown, Menu, Plus, RefreshCw, Search, ShieldCheck, Sparkles, X } from 'lucide-react';
import { OreClient } from '@ore/sdk';
import type { AccessProfile, Artifact, ConversationSummary, Job, JsonObject, Model, OreEvent, Resource, Rune, Source } from '@ore/sdk';
import { Empty, ErrorNotice, Field, Logo, Spinner, Status } from './components/Common';
import MissionForm from './components/MissionForm';
import ChatView from './components/ChatView';
import ConversationLibrary from './components/ConversationLibrary';
import JobDetail from './components/JobDetail';
import BrowserView from './components/BrowserView';
import RunesView from './components/RunesView';
import {MissionProgress,SourcePolicyEditor} from './components/MissionProgress';
import HandoffsView from './components/HandoffsView';
import ConnectionsView from './components/ConnectionsView';
import { date, download, errorMessage, instructions, jobName, label, record, text } from './lib/format';
type View='chat'|'missions'|'browser'|'runes'|'connections'|'handoffs';
export function routeFromPath(path:string){const parts=path.split(/[?#]/)[0]!.split('/').filter(Boolean);return {view:(parts[0]==='jobs'?'missions':['chat','browser','runes','connections','handoffs'].includes(parts[0]??'')?parts[0]:'chat') as View,id:parts[1]??''};}
const navigation:[View,string,typeof Compass][]=[['chat','Chat',MessageCircle],['missions','Missions',Compass],['handoffs','Needs your input',KeyRound],['browser','Browser',Globe2],['runes','Rune library',BookOpen],['connections','Connections',Link2]];
export default function App(){
 const [theme,setTheme]=useState<'light'|'dark'>(()=>{try{return localStorage.getItem('ore.theme')==='dark'?'dark':'light';}catch{return 'light';}});
 const [conversationSearch,setConversationSearch]=useState('');
 const [serverVersion,setServerVersion]=useState('');
 useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('ore.theme',theme);}catch{/* preference storage optional */}},[theme]);
 const themeToggle=<button className="theme-toggle" aria-label={theme==='light'?'Switch to dark theme':'Switch to light theme'} onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={16}/>:<Sun size={16}/>}<span>{theme==='light'?'Dark appearance':'Light appearance'}</span></button>;
 const [baseUrl,setBaseUrl]=useState(()=>{try{return localStorage.getItem('ore.server')||window.location.origin;}catch{return window.location.origin;}});const tokenRef=useRef('');
 const client=useMemo(()=>new OreClient({baseUrl,token:()=>tokenRef.current}),[baseUrl]);
 const [authenticated,setAuthenticated]=useState(false);const [checking,setChecking]=useState(true);const [view,setView]=useState<View>(()=>routeFromPath(location.pathname).view);const [jobs,setJobs]=useState<Job[]>([]);const [sources,setSources]=useState<Source[]>([]);const [models,setModels]=useState<Model[]>([]);const [runes,setRunes]=useState<Rune[]>([]);const [profiles,setProfiles]=useState<AccessProfile[]>([]);const [workers,setWorkers]=useState<JsonObject[]>([]);const [selected,setSelected]=useState(()=>routeFromPath(location.pathname).view==='missions'?routeFromPath(location.pathname).id:'');const [job,setJob]=useState<Job|null>(null);const [resources,setResources]=useState<Resource[]>([]);const [artifacts,setArtifacts]=useState<Artifact[]>([]);const [events,setEvents]=useState<OreEvent[]>([]);const [streamState,setStreamState]=useState('connecting');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [create,setCreate]=useState(false);const [search,setSearch]=useState('');const [statusFilter,setStatusFilter]=useState('all');const [mobileNav,setMobileNav]=useState(false);const selectedRef=useRef(selected);selectedRef.current=selected;
 const [conversations,setConversations]=useState<ConversationSummary[]>([]);const [conversationId,setConversationId]=useState(()=>routeFromPath(location.pathname).view==='chat'?routeFromPath(location.pathname).id:'');
 const [handoffId,setHandoffId]=useState(()=>routeFromPath(location.pathname).view==='handoffs'?routeFromPath(location.pathname).id:'');const [handoffCount,setHandoffCount]=useState(0);
 function openPath(path:string,push=true){if(push)history.pushState({},'',path);const route=routeFromPath(path);setView(route.view);setConversationId(route.view==='chat'?route.id:'');setSelected(route.view==='missions'?route.id:'');setHandoffId(route.view==='handoffs'?route.id:'');setMobileNav(false);}
 useEffect(()=>{if(!mobileNav)return;const sidebar=document.querySelector<HTMLElement>('.sidebar');sidebar?.querySelector<HTMLButtonElement>('button')?.focus();const close=(event:KeyboardEvent)=>{if(event.key==='Escape'){setMobileNav(false);document.querySelector<HTMLButtonElement>('.mobile-menu')?.focus();}if(event.key==='Tab'&&sidebar){const nodes=[...sidebar.querySelectorAll<HTMLElement>('button,input,summary,a')].filter(node=>node.getClientRects().length>0&&!node.hasAttribute('disabled'));const first=nodes[0],last=nodes.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[mobileNav]);
 useEffect(()=>{const changed=()=>openPath(location.pathname,false);window.addEventListener('popstate',changed);return()=>window.removeEventListener('popstate',changed);},[]);
 useEffect(()=>{if(!authenticated)return;let alive=true;const poll=()=>client.handoffs().then(rows=>{if(alive)setHandoffCount(rows.length);}).catch(()=>undefined);void poll();const timer=setInterval(()=>void poll(),5000);return()=>{alive=false;clearInterval(timer);};},[client,authenticated]);
 useEffect(()=>{let alive=true;void client.health().then(value=>{if(alive)setServerVersion(value.version??'');}).catch(()=>{if(alive)setServerVersion('');});return()=>{alive=false;};},[client,authenticated]);
 const refreshConversations=useCallback(async()=>{setConversations(await client.conversations());},[client]);
 useEffect(()=>{if(!authenticated)return;void refreshConversations().catch(()=>undefined);const timer=setInterval(()=>void refreshConversations().catch(()=>undefined),10000);return()=>clearInterval(timer);},[authenticated,refreshConversations]);
 const refreshJobs=useCallback(async()=>{setJobs(await client.listJobs());},[client]);
 const refreshEnvironment=useCallback(async()=>{const results=await Promise.allSettled([client.sources(),client.models(),client.accessProfiles(),client.workers(),client.runes()]);const setters=[setSources,setModels,setProfiles,setWorkers,setRunes] as ((value:never)=>void)[];const names=['sources','models','access profiles','workers','Runes'];const failures:string[]=[];results.forEach((result,index)=>{if(result.status==='fulfilled')setters[index]!(result.value as never);else failures.push(`${names[index]}: ${errorMessage(result.reason)}`);});if(failures.length)setNotice(`Some connections could not be loaded. ${failures.join(' · ')}`);},[client]);
 const refreshDetail=useCallback(async(id:string)=>{const [fresh,resourceList,artifactList]=await Promise.all([client.getJob(id),client.resources(id),client.artifacts(id)]);if(selectedRef.current!==id)return;setJob(fresh);setResources(resourceList);setArtifacts(artifactList);},[client]);
 useEffect(()=>{let current=true;client.listJobs().then(list=>{if(current){setJobs(list);setAuthenticated(true);}}).catch(()=>{if(current)setAuthenticated(false);}).finally(()=>{if(current)setChecking(false);});return()=>{current=false;};},[client]);
 useEffect(()=>{if(!authenticated)return;void refreshEnvironment();const timer=setInterval(()=>void refreshJobs().catch(cause=>setError(errorMessage(cause))),10000);return()=>clearInterval(timer);},[authenticated,refreshEnvironment,refreshJobs]);
 useEffect(()=>{if(!authenticated||!selected)return;let disposed=false;let reconnect:ReturnType<typeof setTimeout>|undefined;let update:ReturnType<typeof setTimeout>|undefined;const controller=new AbortController();let cursor:string|undefined;setEvents([]);setStreamState('connecting');setJob(null);setResources([]);setArtifacts([]);
 const snapshot=()=>void refreshDetail(selected).catch(cause=>{if(!disposed)setError(errorMessage(cause));});snapshot();
 const listen=async()=>{try{setStreamState('connecting');for await(const event of client.events(selected,{after:cursor,signal:controller.signal})){if(disposed)return;setStreamState('live');cursor=event.id??(text(record(event.data).id,'')||cursor);setEvents(current=>{const key=event.id??record(event.data).id;return key&&current.some(item=>(item.id??record(item.data).id)===key)?current:[...current.slice(-299),event];});if(!update)update=setTimeout(()=>{update=undefined;snapshot();void refreshJobs().catch(()=>undefined);},450);}if(!disposed){setStreamState('reconnecting');reconnect=setTimeout(()=>void listen(),3000);}}catch(cause){if(!disposed){setStreamState('reconnecting');if((cause as {status?:number}).status===401){setError('Your operator session expired. Sign out and connect again.');return;}reconnect=setTimeout(()=>void listen(),3000);}}};void listen();
 const poll=setInterval(snapshot,10000);return()=>{disposed=true;controller.abort();if(reconnect)clearTimeout(reconnect);if(update)clearTimeout(update);clearInterval(poll);};
 },[authenticated,client,selected,refreshDetail,refreshJobs]);
 async function connect(token:string,url:string){const next=new OreClient({baseUrl:url,token});await next.request('/v1/auth/login',{method:'POST',body:JSON.stringify({token})});const list=await next.listJobs();tokenRef.current=token;setBaseUrl(url.replace(/\/+$/,''));try{localStorage.setItem('ore.server',url);}catch{/* optional server preference */}setJobs(list);setAuthenticated(true);setChecking(false);}
 async function logout(){try{await client.request('/v1/auth/logout',{method:'POST',body:'{}'});}catch(cause){setError(`Could not close the server session: ${errorMessage(cause)}`);return;}tokenRef.current='';setAuthenticated(false);setSelected('');setEvents([]);setJobs([]);setJob(null);}
 async function createMission(mission:JsonObject,start:boolean){const created=await client.createJob(mission);setCreate(false);openPath('/jobs/'+created.id);await refreshJobs();if(start){try{await client.action(created.id,'run');await refreshJobs();}catch(cause){setError(`Mission created, but it could not start: ${errorMessage(cause)}`);}}}
 async function action(value:'run'|'pause'|'resume'|'refresh'|'audit'){if(!selected)return;setBusy(true);setError('');try{const result=await client.action(selected,value);setNotice(value==='audit'?'Coverage audit completed.':value==='refresh'?'A new observation was requested.':`${label(value)} requested.`);const newId=text(result.id??result.job_id,'');if(value==='refresh'&&newId&&newId!==selected)setSelected(newId);else await refreshDetail(selected);await refreshJobs();}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}
 async function revise(value:string){try{await client.reviseJob(selected,{instructions:value});await refreshDetail(selected);await refreshJobs();setNotice('Mission instructions updated. The server recorded a new revision.');}catch(cause){setError(errorMessage(cause));throw cause;}}
 async function exportResult(){setBusy(true);try{download(await client.exportJob(selected),`ore-${selected}.jsonl`);}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}
 async function downloadArtifact(artifact:Artifact){setBusy(true);try{download(await client.artifactFile(selected,artifact.id),text(artifact.filename??artifact.name,`${artifact.role??'artifact'}-${artifact.id}`));}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}
 function navigate(next:View){openPath(next==='chat'?'/':next==='missions'?'/jobs':'/'+next);}
 if(checking)return <div className="boot-screen"><Logo/><Spinner/><p>Connecting to your retrieval workspace…</p></div>;
 if(!authenticated)return <><div className="theme-login">{themeToggle}</div><Login baseUrl={baseUrl} onConnect={connect}/></>;
 const filtered=jobs.filter(item=>(statusFilter==='all'||item.status===statusFilter)&&`${jobName(item)} ${instructions(item)}`.toLowerCase().includes(search.toLowerCase()));const active=jobs.filter(item=>item.status==='running').length;const waiting=jobs.filter(item=>['awaiting_user','awaiting_auth'].includes(item.status??'')).length;
 return <div className={`app-shell ${view==='chat'?'app-shell-chat':''}`}><a className="skip-link" href="#main-workspace">Skip to workspace</a><aside className={`sidebar ${mobileNav?'mobile-open':''}`} aria-label="Workspace navigation"><Logo/><button className="button primary new-mission-button" onClick={()=>openPath('/')}><Plus size={18}/>New chat</button><div className="conversation-search"><Search size={15}/><input aria-label="Search conversations" placeholder="Search conversations" value={conversationSearch} onChange={event=>setConversationSearch(event.target.value)}/></div><nav className="primary-navigation">{navigation.filter(([key])=>key==='missions'||key==='handoffs').map(([key,caption,Icon])=><button key={key} className={view===key?'active':''} onClick={()=>navigate(key)}><Icon size={17}/><span>{caption}</span>{key==='missions'&&jobs.length>0&&<em>{jobs.length}</em>}{key==='handoffs'&&handoffCount>0&&<em className="attention-count">{handoffCount}</em>}</button>)}</nav><ConversationLibrary client={client} conversations={conversations} selected={view==='chat'?conversationId:''} search={conversationSearch} onNavigate={openPath} onChanged={()=>void refreshConversations().catch(cause=>setError(errorMessage(cause)))}/><div className="sidebar-bottom"><details className="sidebar-tools"><summary>Workspace tools<ChevronDown size={15}/></summary><nav>{navigation.filter(([key])=>['browser','runes','connections'].includes(key)).map(([key,caption,Icon])=><button key={key} className={view===key?'active':''} onClick={()=>navigate(key)}><Icon size={17}/><span>{caption}</span></button>)}</nav></details><button className="legacy-mission-button" onClick={()=>setCreate(true)}><Compass size={16}/>New mission</button>{themeToggle}<button className="logout-button" onClick={()=>void logout()}><LogOut size={15}/>Disconnect operator</button><p>OPEN RETRIEVAL ENGINE <span>{serverVersion?'v'+serverVersion:'Version unavailable'}</span></p></div></aside>
 {mobileNav&&<button className="nav-scrim" aria-label="Close navigation" onClick={()=>setMobileNav(false)}/>}<div className="main-shell" id="main-workspace" tabIndex={-1}><header className="topbar"><button className="mobile-menu icon-button" onClick={()=>setMobileNav(!mobileNav)} aria-label="Toggle navigation"><Menu size={20}/></button><div className="breadcrumbs">Workspace<ChevronRight size={12}/><strong>{navigation.find(item=>item[0]===view)?.[1]}</strong>{selected&&view==='missions'&&<><ChevronRight size={12}/><span>Mission</span></>}</div><div className="topbar-right"><span><span className="connection-dot online"/>Server connected</span><button className="operator-avatar" title="Authenticated operator" onClick={()=>navigate('connections')}>OP</button></div></header>
 {error&&<div className="global-notice"><ErrorNotice message={error} onClose={()=>setError('')}/></div>}{notice&&<div className="toast" role="status"><ShieldCheck size={16}/><span>{notice}</span><button className="icon-button" aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={14}/></button></div>}
 {view==='missions'&&selected&&job&&<div className="job-extras"><MissionProgress job={job} onNavigate={openPath}/><SourcePolicyEditor client={client} job={job} sources={sources} onChanged={()=>void refreshDetail(job.id)}/></div>}
 {view==='missions'&&(selected?(job?<JobDetail job={job} resources={resources} artifacts={artifacts} events={events} streamState={streamState} busy={busy} onBack={()=>openPath('/jobs')} onAction={value=>void action(value)} onRevise={revise} onExport={()=>void exportResult()} onDownload={artifact=>void downloadArtifact(artifact)}/>:<div className="page"><Empty icon={<Spinner/>} title="Loading mission">Fetching the inventory and current execution state.</Empty></div>):<section className="page"><header className="page-heading"><div><div className="eyebrow">YOUR RETRIEVAL OPERATIONS</div><h1>Missions</h1><p>Turn a research question into a traceable collection.</p></div><button className="button outline" onClick={()=>void refreshJobs().catch(cause=>setError(errorMessage(cause)))}><RefreshCw size={15}/>Refresh</button></header>
 {!jobs.length&&<div className="panel info-callout"><KeyRound size={18}/><span>First visit? Connect only the providers you need. Existing accounts and pending approvals are managed in Connections.</span><button className="button outline" onClick={()=>navigate('connections')}>Set up selected sources</button></div>}
 <div className="overview-strip"><div><span className="overview-icon"><Compass size={19}/></span><span><strong>{jobs.length}</strong><small>Total missions</small></span></div><div><span className="overview-icon green"><Activity size={19}/></span><span><strong>{active}</strong><small>Running now</small></span></div><div><span className="overview-icon amber"><KeyRound size={18}/></span><span><strong>{waiting}</strong><small>Need your input</small></span></div><div><span className="overview-icon"><Cpu size={19}/></span><span><strong>{workers.length}</strong><small>Registered workers</small></span></div></div>
 {!jobs.length?<div className="mission-welcome panel"><div className="welcome-copy"><div className="eyebrow">DEFINE. RETRIEVE. VERIFY.</div><h2>Your next corpus<br/>starts with a mission.</h2><p>Tell ORE what to find. Agents navigate sources, collect original files and preserve the evidence behind every result.</p><button className="button primary" onClick={()=>setCreate(true)}><Plus size={17}/>Create your first mission<ArrowRight size={16}/></button><div className="welcome-tags"><span><Layers3 size={14}/>Multiple sources</span><span><FileGlyph/>Main + supplement</span><span><ShieldCheck size={14}/>Verifiable artifacts</span></div></div><div className="welcome-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="ore-core"><Logo/></div><span className="orbit-node node-a"><Database size={22}/></span><span className="orbit-node node-b"><Globe2 size={23}/></span><span className="orbit-node node-c"><ShieldCheck size={22}/></span><div className="art-caption">ONE MISSION. CONNECTED EVIDENCE.</div></div></div>:<><div className="list-toolbar"><div className="filter-tabs"><button className={statusFilter==='all'?'active':''} onClick={()=>setStatusFilter('all')}>All missions <span>{jobs.length}</span></button><button className={statusFilter==='running'?'active':''} onClick={()=>setStatusFilter('running')}>Running</button><button className={statusFilter==='awaiting_user'?'active':''} onClick={()=>setStatusFilter('awaiting_user')}>Needs input</button></div><div className="search-field"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a mission…" aria-label="Find a mission"/></div></div><div className="mission-grid">{filtered.map(item=><button className="mission-card" key={item.id} onClick={()=>openPath('/jobs/'+item.id)}><div className="mission-card-top"><span className="mission-card-icon"><Compass size={21}/></span><Status value={item.status}/></div><h3>{jobName(item)}</h3><p>{instructions(item)}</p><div className="mission-sources">{(Array.isArray(record(item.mission).sources)?record(item.mission).sources as string[]:[]).slice(0,3).map(source=><span key={source}>{label(source)}</span>)}</div><footer><time>{date(item.updated_at??item.created_at)}</time><span>Inspect mission<ArrowRight size={14}/></span></footer></button>)}</div>{!filtered.length&&<Empty icon={<Search size={24}/>} title="No missions match this view">Change the filter or create a new mission.</Empty>}</>}
 <div className="workspace-footer"><span><ShieldCheck size={14}/>Original files. Explicit coverage. Preserved provenance.</span><button className="text-button" onClick={()=>navigate('runes')}>Explore Rune protocols<ArrowRight size={14}/></button></div></section>)}
 {view==='chat'&&<ChatView client={client} id={conversationId} models={models} onNavigate={openPath} onChanged={()=>void refreshConversations().catch(()=>undefined)}/>}
 {view==='handoffs'&&<HandoffsView client={client} profiles={profiles} id={handoffId} onNavigate={openPath}/>}
 {view==='browser'&&<BrowserView client={client} profiles={profiles}/>} {view==='runes'&&<RunesView client={client}/>} {view==='connections'&&<ConnectionsView client={client} profiles={profiles} sources={sources} onNavigate={openPath} onChanged={()=>void refreshEnvironment()}/>}
 </div>{create&&<MissionForm sources={sources} models={models} profiles={profiles} runes={runes} onClose={()=>setCreate(false)} onCreate={createMission}/>}</div>;
}
function FileGlyph(){return <Layers3 size={14}/>;}
function Login({baseUrl,onConnect}:{baseUrl:string;onConnect:(token:string,url:string)=>Promise<void>}){const [token,setToken]=useState('');const [server,setServer]=useState(baseUrl);const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{await onConnect(token.trim(),server.trim());setToken('');}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}return <div className="login-page"><div className="login-brand"><Logo/><span>OPEN RETRIEVAL ENGINE</span></div><main className="login-layout"><div className="login-story"><div className="eyebrow">A WORKSPACE FOR DISCOVERY</div><h1>From scattered sources<br/>to a corpus you<br/><em>can account for.</em></h1><p>Protocol-guided agents. Original files and supplements. Every step connected to its evidence.</p><div className="login-features"><span><Sparkles size={17}/>LLM agents that follow your intent</span><span><ShieldCheck size={17}/>A clear record of what was retrieved</span><span><Globe2 size={17}/>Your browser, your institution access</span></div></div><form className="login-card" onSubmit={submit}><div className="login-key"><KeyRound size={23}/></div><h2>Connect to ORE</h2><p>Use the operator token configured for your ORE server.</p><Field label="Server address"><input type="url" required value={server} onChange={e=>setServer(e.target.value)} autoComplete="url"/></Field><Field label="Operator token"><input type="password" required autoComplete="current-password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Enter your ORE token"/></Field>{error&&<ErrorNotice message={error}/>}<button className="button primary full-width" disabled={busy}>{busy?<Spinner/>:<ArrowRight size={17}/>}Connect workspace</button><small className="login-note">This is your ORE operator token, not a Codex or publisher credential.</small></form></main><footer>ORE / OPEN RETRIEVAL ENGINE <span>Define the protocol. Retrieve with evidence.</span></footer></div>;}
