import { useCallback, useEffect, useRef, useState } from 'react';
import { Globe2, Hand, Link2, Monitor, Play, RefreshCw, WifiOff } from 'lucide-react';
import { OreClient } from '@ore/sdk';
import type { AccessProfile, BrowserFrame, BrowserInput, BrowserSession } from '@ore/sdk';
import { Empty, ErrorNotice, Field, Spinner } from './Common';
import { errorMessage, record, text } from '../lib/format';
import { canControl, framePoint } from '../lib/browser';
interface Props{client:OreClient;profiles:AccessProfile[];initialSession?:string;embedded?:boolean;}

export function browserFrameImageSource(frame:Pick<BrowserFrame,'data'>&{mime_type?:unknown}):string{
 const data=frame.data.trim();
 if(data.startsWith('data:'))return data;
 const declared=typeof frame.mime_type==='string'?frame.mime_type.split(';',1)[0].trim().toLowerCase():'';
 const mime=data.startsWith('iVBORw0KGgo')?'image/png':data.startsWith('/9j/')?'image/jpeg':['image/png','image/jpeg','image/webp'].includes(declared)?declared:'image/jpeg';
 return `data:${mime};base64,${data}`;
}
export default function BrowserView({client,profiles,initialSession,embedded}:Props){
 const [sessions,setSessions]=useState<BrowserSession[]>([]);const [selected,setSelected]=useState(initialSession??'');const [frame,setFrame]=useState<BrowserFrame|null>(null);const [connection,setConnection]=useState('connecting');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [url,setUrl]=useState('');const [profile,setProfile]=useState('');const [showOpen,setShowOpen]=useState(false);
 const canvas=useRef<HTMLCanvasElement>(null);const socket=useRef<WebSocket|null>(null);const latest=useRef<BrowserFrame|null>(null);const lastError=useRef('');
 const load=useCallback(async()=>{try{const list=await client.browserSessions();setSessions(list);setSelected(current=>list.some(s=>s.id===current)?current:initialSession??list[0]?.id??'');}catch(cause){setError(errorMessage(cause));}},[client,initialSession]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),10000);return()=>clearInterval(timer);},[load]);
 useEffect(()=>{
   latest.current=null;setFrame(null);if(!selected){setConnection('idle');return;}
   let disposed=false;let retry:ReturnType<typeof setTimeout>|undefined;
   const connect=()=>{if(disposed)return;setConnection('connecting');const config=client.browserSocket(selected);const ws=new WebSocket(config.url,config.protocols);socket.current=ws;
     ws.onopen=()=>{if(disposed)return;setConnection('connected');lastError.current='';};
     ws.onmessage=event=>{if(disposed)return;try{const value=JSON.parse(String(event.data));if(value.type==='frame'&&typeof value.data==='string'&&value.width>0&&value.height>0&&value.width<=10000&&value.height<=10000){latest.current=value as BrowserFrame;setFrame(value as BrowserFrame);}else if(value.type==='error'){lastError.current=text(value.message??value.error,'Browser operation failed.');setError(lastError.current);}else if((value.type==='control'||value.type==='state')&&latest.current){const current={...latest.current,...value.session,...(value.control?{control:value.control}:{}),...(typeof value.epoch==='number'?{epoch:value.epoch}:{})};latest.current=current;setFrame(current);}}catch{setError('Received an invalid browser stream message.');}};
     ws.onerror=()=>{if(!disposed)setConnection('disconnected');};ws.onclose=()=>{if(disposed)return;setConnection('disconnected');retry=setTimeout(connect,3000);};
   };connect();return()=>{disposed=true;if(retry)clearTimeout(retry);socket.current?.close();socket.current=null;latest.current=null;};
 },[client,selected]);
 useEffect(()=>{if(!frame)return;const image=new Image();image.onload=()=>{if(latest.current?.frame_id!==frame.frame_id)return;const node=canvas.current;if(!node)return;node.width=frame.width;node.height=frame.height;node.getContext('2d')?.drawImage(image,0,0,frame.width,frame.height);};image.src=browserFrameImageSource(frame);},[frame]);
 const send=useCallback((payload:Omit<BrowserInput,'type'|'epoch'|'frame_id'>)=>{const current=latest.current;const ws=socket.current;if(!current||!ws||!canControl(current,ws.readyState))return;ws.send(JSON.stringify({type:'input',...payload,frame_id:current.frame_id,epoch:current.epoch}));},[]);
 useEffect(()=>{const node=canvas.current;if(!node)return;const wheel=(event:WheelEvent)=>{const current=latest.current;if(!current||!canControl(current,socket.current?.readyState??3))return;event.preventDefault();const point=framePoint(event.clientX,event.clientY,node.getBoundingClientRect(),current);if(point)send({action:'scroll',...point,deltaY:Math.round(event.deltaY*(event.deltaMode===1?16:event.deltaMode===2?current.height:1))});};node.addEventListener('wheel',wheel,{passive:false});return()=>node.removeEventListener('wheel',wheel);},[selected,frame!==null,send]);
 async function control(action:'takeover'|'resume'){if(!selected)return;if(action==='resume'){const requests=await client.handoffs(session?.job_id);const request=requests.find(h=>h.session_id===selected);if(request){window.location.assign(request.href);return;}}setBusy(true);setError('');try{await client.browserControl(selected,action);await load();}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}
 async function open(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const session=await client.request<BrowserSession>('/v1/browser/sessions',{method:'POST',body:JSON.stringify({url,...(profile?{access_profile_ref:profile}:{})})});await load();setSelected(session.id);setShowOpen(false);}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}
 const session=sessions.find(s=>s.id===selected);const human=frame?.control==='human';const desktop=session?.transport==='desktop_chrome';
 return <section className={`page browser-page ${embedded?'embedded-browser':''}`}><header className="page-heading"><div><div className="eyebrow">HUMAN + AGENT</div><h1>Browser workspace</h1><p>Observe the same session. Take control when your input is needed.</p></div><button className="button primary" onClick={()=>setShowOpen(!showOpen)}><Globe2 size={16}/>Open browser</button></header>
 {error&&<ErrorNotice message={error} onClose={()=>setError('')}/>}
 {showOpen&&<form className="panel open-browser-form" onSubmit={open}><Field label="Start URL"><input type="url" required value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://your-journal.org"/></Field><Field label="Access profile"><select value={profile} onChange={e=>setProfile(e.target.value)}><option value="">Public access</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name||p.id}</option>)}</select></Field><button className="button primary" disabled={busy}>{busy?<Spinner/>:<Link2 size={16}/>}Open session</button></form>}
 <BrowserResourceWarning session={session}/>
 <div className="browser-layout"><aside className="panel session-list"><div className="panel-heading"><h3>Sessions <span>{sessions.length}</span></h3><button className="icon-button" aria-label="Refresh sessions" onClick={()=>void load()}><RefreshCw size={15}/></button></div>{sessions.map(s=><button className={`session-item ${s.id===selected?'active':''}`} key={s.id} onClick={()=>setSelected(s.id)}><Monitor size={17}/><span><strong>{text(s.title,s.id.slice(0,12))}</strong><small>{text(s.url,'Waiting for navigation')}</small><em>{s.control==='human'?'You have control':'Agent control'}</em></span></button>)}{!sessions.length&&<p className="session-empty">Open a browser or launch a mission to create a session.</p>}</aside>
 <div className="browser-main panel"><div className="browser-toolbar"><div className="browser-address"><Globe2 size={14}/><span>{text(session?.url,'No browser session')}</span></div><span className={`connection-dot ${connection==='connected'?'online':''}`} title={connection}/>{selected&&<button className={`button ${human?'subtle':'primary'} compact`} onClick={()=>void control(human?'resume':'takeover')} disabled={busy||connection!=='connected'}>{busy?<Spinner/>:human?<Play size={14}/>:<Hand size={14}/>} {human?'Return to agent':'Take control'}</button>}</div>
 {!selected?<Empty icon={<Monitor size={28}/>} title="A shared view of the work">Browser sessions stay on the server and retain their institution access.</Empty>:<>{desktop&&<div className="control-banner" role="note"><Monitor size={14}/><span><strong>ORE virtual desktop · Chrome</strong> — Screenshot of Chrome and its toolbar. Take control to click, type, paste, or scroll on the desktop.</span></div>}<div className={`control-banner ${human?'human':''}`}>{human?<><Hand size={14}/> You have control. Click the page to type. Paste is supported.</>:<><Monitor size={14}/> {connection==='connected'?'Agent is in control. Take control to interact.':'Connecting to the browser session…'}</>}</div><div className="browser-canvas-wrap">{!frame?<Empty icon={connection==='disconnected'?<WifiOff size={25}/>:<Spinner/>} title={connection==='disconnected'?'Reconnecting…':'Waiting for the first frame'}>The session stays available while the connection recovers.</Empty>:<canvas ref={canvas} tabIndex={human?0:-1} aria-label={desktop?'ORE virtual desktop screen':'Remote browser page'} className={human?'controllable':''} onClick={event=>{const current=latest.current;if(!current)return;const point=framePoint(event.clientX,event.clientY,event.currentTarget.getBoundingClientRect(),current);if(point){event.currentTarget.focus();send({action:'click',...point});}}} onKeyDown={event=>{if(!human)return;if(event.metaKey||event.ctrlKey){if(event.key.toLowerCase()==='v')return;event.preventDefault();send({action:'key',key:`${event.ctrlKey?'Control':'Meta'}+${event.key}`});return;}event.preventDefault();if(event.key.length===1)send({action:'text',text:event.key});else if(!['Shift','Alt','Meta','Control'].includes(event.key))send({action:'key',key:event.key});}} onPaste={event=>{if(!human)return;event.preventDefault();send({action:'text',text:event.clipboardData.getData('text/plain')});}}/>}</div><footer className="browser-footer"><span>{connection==='connected'?'Live connection':'Connection interrupted'}</span><span>{frame?`${frame.width} × ${frame.height} · Control epoch ${frame.epoch}`:'Session state is preserved'}</span></footer></>}
 </div></div></section>;
}

export function BrowserResourceWarning({session}:{session?:BrowserSession}){
 const diagnostics=record(session?.network_diagnostics);
 const blocked=Array.isArray(diagnostics.blocked_requests)?diagnostics.blocked_requests.slice(-20):[];
 if(!blocked.length)return null;
 return <div className="browser-resource-warning" role="alert"><strong>ORE blocked a page resource</strong><p>This page may be incomplete. These requests were blocked by ORE:</p><ul>{blocked.map((item,index)=>{const request=record(item);let host='Page resource';try{host=new URL(text(request.url,'')).host;}catch{/* Invalid URLs are not shown. */}return <li key={index}><code>{host}</code><span>{text(request.reason,'The request did not meet this mission’s access settings.')}</span></li>;})}</ul></div>;
}
