import {useEffect,useState} from 'react';
import type {Handoff,OreClient} from '@ore/sdk';
import {errorMessage} from '../lib/format';
type Pair={pair_id:string;token:string;expires_at:number;origins:string[]};
export default function ChromeCompanion({client,handoff,onAttached}:{client:OreClient;handoff:Handoff;onAttached:()=>Promise<void>}){
 const [pair,setPair]=useState<Pair|null>(null),[connected,setConnected]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!pair)return;let stopped=false;const check=()=>void client.request<{connected:boolean}>(`/v1/companion/pairs/${pair.pair_id}`).then(r=>{if(!stopped)setConnected(r.connected);}).catch(e=>{if(!stopped)setError(errorMessage(e));});check();const timer=setInterval(check,3000);return()=>{stopped=true;clearInterval(timer);};},[client,pair]);
 async function download(){try{const r=await client.response('/v1/companion/package'),url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='ore-chrome-companion.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(errorMessage(e));}}
 async function create(){setBusy(true);setError('');try{setPair(await client.request<Pair>('/v1/companion/pair',{method:'POST',body:JSON.stringify({handoff_id:handoff.id})}));setConnected(false);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function attach(){if(!pair)return;setBusy(true);setError('');try{const fresh=await client.handoff(handoff.id);await client.request(`/v1/companion/pairs/${pair.pair_id}/attach`,{method:'POST',body:JSON.stringify({expected_version:fresh.state_version,idempotency_key:crypto.randomUUID()})});setPair(null);await onAttached();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 const code=pair?JSON.stringify({...pair,server:window.location.origin}):'';
 return <details className="panel"><summary>Use Chrome on this PC</summary><p>Install the companion in the Chrome that can open this journal. It connects one new tab to this mission. Existing tabs and browser cookies are not transferred to ORE.</p><ol><li><button className="button outline" onClick={()=>void download()}>Download Chrome companion</button> Unzip the file.</li><li>Open <code>chrome://extensions</code>, enable Developer mode, select Load unpacked, and choose the unzipped folder.</li><li><button className="button outline" disabled={busy} onClick={()=>void create()}>Create pairing code</button> Paste the code into the extension and select Connect dedicated tab.</li></ol>{pair&&<><p>The code expires in five minutes. Do not share it.</p><textarea aria-label="Chrome pairing code" readOnly value={code} rows={5} style={{width:'100%'}}/><p>Permitted mission origins: {pair.origins.join(', ')}</p><p role="status">{connected?'Chrome connected':'Waiting for Chrome connection'}</p><button className="button primary" disabled={!connected||busy} onClick={()=>void attach()}>Use connected Chrome for this request</button></>}{handoff.browser_transport==='chrome_companion'&&<p>Connected Chrome is attached to this request. Complete any login in its dedicated tab, then use Verify &amp; resume. Automatic browsing still follows the mission’s API/browser settings.</p>}{error&&<p role="alert">{error}</p>}</details>;
}
