import {CheckCircle2,ChevronRight,FileCheck2,Layers3} from 'lucide-react';
import {record,text,label} from '../lib/format';
import {Status} from './Common';

function count(value:unknown):number|null{return typeof value==='number'&&Number.isFinite(value)&&value>=0?value:null;}
function shown(value:unknown){return count(value)===null?'—':String(value);}
export function CollectionProgress({value,compact=false}:{value:unknown;compact?:boolean}){
 const data=record(value);if(!Object.keys(data).length)return null;
 const denominator=record(data.denominator),resources=record(data.resources),issues=record(data.issues),gaps=record(data.gaps),supplements=record(data.supplements),artifacts=record(data.artifacts);
 if(data.kind==='artifacts')return compact?<div className="collection-compact"><FileCheck2 size={15}/><span>{shown(artifacts.verified)} outputs verified</span></div>:<section className="collection-progress" aria-label="Output verification"><header><div><span className="chat-card-caption">Outputs</span><h3>Output verification</h3></div><FileCheck2 size={19}/></header><div className="collection-metrics"><div><strong>{shown(artifacts.verified)}</strong><small>Verified outputs</small></div><div><strong>{shown(artifacts.known)}</strong><small>Recorded files</small></div></div><p className="collection-basis">File verification and workflow completion checks are tracked separately.</p></section>;
 const roles=Array.isArray(data.roles)?data.roles.map(record):[];
 const total=count(denominator.total),complete=count(resources.complete),sealed=denominator.status==='sealed';
 const basis=text(denominator.basis,'The collection scope is still being established.');
 const inventoryLabel=sealed?'Scope confirmed':denominator.status==='provisional'?'Confirming scope':'Discovering scope';
 if(compact)return <div className="collection-compact"><Layers3 size={15}/><span>{sealed&&total!==null&&complete!==null?`${complete} / ${total} items verified`:inventoryLabel}</span>{count(gaps.count)!==null&&Number(gaps.count)>0&&<small>{String(gaps.count)} unresolved</small>}</div>;
 return <section className="collection-progress" aria-label="Collection progress"><header><div><span className="chat-card-caption">Collection</span><h3>{inventoryLabel}</h3></div><Status value={sealed?'verified':'pending'}/></header><p className="collection-basis">{basis}</p><div className="collection-metrics"><div><strong>{shown(resources.complete)}{sealed&&total!==null&&<span> / {total}</span>}</strong><small>Items fully verified</small></div><div><strong>{shown(resources.included)}</strong><small>Included items</small></div><div><strong>{shown(resources.unresolved)}</strong><small>Awaiting resolution</small></div></div>{sealed&&total!==null&&total>0&&complete!==null&&<progress aria-label="Verified collection items" max={total} value={Math.min(complete,total)}/>}<div className="collection-role-list">{roles.map(role=><div key={text(role.role)}><FileCheck2 size={16}/><strong>{label(text(role.role,'Files'))}</strong><span>{shown(role.verified)} verified{count(role.expected)!==null?` / ${role.expected} required`:' · requirement count open'}</span>{Number(role.unknown)>0&&<small>{String(role.unknown)} unknown</small>}{Number(role.missing)>0&&<small>{String(role.missing)} remaining</small>}</div>)}</div>{roles.some(role=>role.role==='supplement')&&Object.keys(supplements).length>0&&<div className="supplement-status"><span>{shown(supplements.none_confirmed)} items confirmed without supplements</span><span>{shown(supplements.inventory_unknown)} supplement inventories still unknown</span></div>}<details><summary>Scope and unresolved items<ChevronRight size={14}/></summary><dl><div><dt>Discovered items</dt><dd>{shown(resources.discovered)}</dd></div>{Object.keys(issues).length>0&&<div><dt>Issues confirmed</dt><dd>{shown(issues.complete)}{count(issues.total)!==null?` / ${issues.total}`:' · total not confirmed'}</dd></div>}{Object.entries(record(gaps.by_kind)).map(([kind,value])=><div key={kind}><dt>{label(kind)}</dt><dd>{String(value)}</dd></div>)}</dl><p>Counts refer to the requested scope. A missing supplementary link does not establish that no supplement exists.</p></details>{sealed&&total!==null&&complete===total&&Number(gaps.count)===0&&<p className="collection-verified"><CheckCircle2 size={15}/>All declared requirements in this scope are verified.</p>}</section>;
}
