import {useCallback,useEffect,useRef,useState} from 'react';
import {ExternalLink,KeyRound,Link2,RefreshCw,ShieldCheck,X} from 'lucide-react';
import type {AccessProfile,ConnectionCard,OreClient,ProviderStatus,Source,SourceQuota} from '@ore/sdk';
import {ErrorNotice,Field,Spinner,Status} from './Common';
import {date,errorMessage,label,safeUrl} from '../lib/format';
import {ConnectionEnrollment} from './ConnectionEnrollment';

const captions:Record<string,string>={start_login:'Sign in with provider',cancel:'Cancel',refresh:'Check status',verify:'Verify API',mark_pending:'Mark approval pending',open_provider:'Open provider setup',request_agent:'Ask ORE to assist'};
const providerNames:Record<string,string>={codex:'Codex',claude:'Claude Code',claude_code:'Claude Code',openai:'OpenAI API',anthropic:'Anthropic API'};
const messages:Record<string,string>={login_process_restarted:'The login session ended. Start provider sign-in again.',connection_action_failed:'The connection step failed. Check status before trying again.',existing_account_connected:'Your existing account is connected.',complete_official_sign_in:'Complete sign-in on the official provider website.',agent_stop_not_confirmed:'Waiting for the setup agent to confirm it stopped.',pending_operation_excluded_from_admission:'This API operation is excluded while approval is pending.',connect_model_before_optional_agent:'Connect a model account before requesting setup assistance.',select_explicit_claude_model:'Choose a Claude model before requesting setup assistance.',credential_stored_operation_unverified:'Credential saved. Access will be verified when the operation runs.',credential_write_needs_review:'The credential update needs review. Check connection status.',login_code_not_accepted:'The authorization code was not accepted. Start a fresh sign-in.',source_operation_checked:'The API check finished. The connection status shows whether this operation is available.',setup_complete_verify_connection:'Setup is complete. Verify the API to check whether collection is available.',provider_setup_resumed:'Provider setup resumed using the details you supplied.',complete_reviewed_provider_step:'Review the pending provider action below to continue setup.',review_provider_form_action_first:'A provider action is waiting for your review. Approve or decline it below.',provider_setup_needs_review:'Provider setup needs attention. Review the latest action or open its browser.'};
function quotaDate(value:unknown){return date(typeof value==='number'?new Date(value<1e12?value*1000:value).toISOString():value);}
const name=(provider:string)=>providerNames[provider]??label(provider);
function officialLogin(value:string|undefined){const safe=safeUrl(value);if(!safe)return null;const url=new URL(safe,location.origin);return url.protocol==='https:'&&['auth.openai.com','auth0.openai.com','auth.anthropic.com','chatgpt.com','platform.openai.com','claude.ai','console.anthropic.com','platform.claude.com'].includes(url.hostname)?url.href:null;}

/** Server cards survive reconnects. Only public status is copied into the chat UI. */
export function ConnectionCards({client,conversationId,open,onClose,onNavigate,refreshKey,onConnectionsChange,agentBackend='codex',agentModel,selectedProfile,onSelectProfile}:{client:OreClient;conversationId?:string;open:boolean;onClose:()=>void;onNavigate:(path:string)=>void;refreshKey?:string|number;onConnectionsChange?:(cards:ConnectionCard[])=>void;agentBackend?:string;agentModel?:string;selectedProfile?:string;onSelectProfile?:(id:string)=>void}){
 const generation=useRef(0);
 const [cards,setCards]=useState<ConnectionCard[]>([]),[providers,setProviders]=useState<ProviderStatus[]>([]),[sourceQuotas,setSourceQuotas]=useState<SourceQuota[]>([]);
 const [sources,setSources]=useState<Source[]>([]),[profiles,setProfiles]=useState<AccessProfile[]>([]);
 const [provider,setProvider]=useState('codex'),[profile,setProfile]=useState('public'),[operation,setOperation]=useState('search');
 const [error,setError]=useState(''),[disconnected,setDisconnected]=useState(false),[busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{const epoch=generation.current;const results=await Promise.allSettled([client.connections(conversationId),client.providerStatusSnapshot()]);if(epoch!==generation.current)return;if(results[0].status==='fulfilled'){setCards(current=>results[0].status==='fulfilled'?results[0].value.map(incoming=>{const existing=current.find(item=>item.id===incoming.id);return existing&&existing.state_version>incoming.state_version?existing:incoming;}):current);setDisconnected(false);}else setDisconnected(true);if(results[1].status==='fulfilled'){setProviders(results[1].value.providers??[]);setSourceQuotas(results[1].value.source_quotas??[]);}},[client,conversationId]);
 useEffect(()=>{generation.current++;let alive=true;const update=()=>{if(alive)void refresh();};setCards([]);update();const timer=setInterval(update,5000);return()=>{alive=false;generation.current++;clearInterval(timer);};},[refresh]);
 useEffect(()=>{if(refreshKey!==undefined)void refresh();},[refreshKey,refresh]);
 useEffect(()=>{if(!open)return;let alive=true;void Promise.allSettled([client.sources(),client.accessProfiles()]).then(results=>{if(!alive)return;if(results[0].status==='fulfilled')setSources(results[0].value);if(results[1].status==='fulfilled')setProfiles(results[1].value);});return()=>{alive=false;};},[client,open]);
 useEffect(()=>{onConnectionsChange?.(cards);},[cards,onConnectionsChange]);
 useEffect(()=>{if(selectedProfile)setProfile(selectedProfile);},[selectedProfile]);
 const update=(card:ConnectionCard)=>setCards(rows=>rows.some(row=>row.id===card.id)?rows.map(row=>row.id===card.id&&row.state_version<=card.state_version?card:row):[...rows,card]);
 async function create(){setBusy(true);setError('');try{update(await client.createConnection({provider,...(conversationId?{conversation_id:conversationId}:{}),...(!['codex','claude','openai','anthropic'].includes(provider)?{access_profile_ref:profile,operation}:{})}));}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}
 if(!open&&!cards.length&&!providers.length&&!sourceQuotas.length)return null;
 return <section className="chat-connections" aria-label="Connections and account usage">
  {open&&<div className="connection-setup"><header><div><Link2 size={17}/><strong>Connect your tools</strong></div><button className="icon-button" aria-label="Close connection setup" onClick={onClose}><X size={17}/></button></header><p>Connect a model account or a source here. Required steps stay with this conversation.</p><div className="connection-setup-fields"><Field label="Provider"><select value={provider} onChange={event=>setProvider(event.target.value)}><option value="codex">Codex</option><option value="claude">Claude Code</option><option value="openai">OpenAI API</option><option value="anthropic">Anthropic API</option>{sources.filter(source=>!['codex','claude','openai','anthropic'].includes(source.id)).map(source=><option key={source.id} value={source.id}>{source.name??label(source.id)}</option>)}</select></Field>{!['codex','claude','openai','anthropic'].includes(provider)&&<><Field label="Access profile"><select value={profile} onChange={event=>setProfile(event.target.value)}><option value="public">Public</option>{profiles.filter(item=>item.id!=='public').map(item=><option key={item.id} value={item.id}>{item.name??item.id}</option>)}</select></Field><Field label="Source operation"><select value={operation} onChange={event=>setOperation(event.target.value)}><option value="search">Search API</option><option value="resolve">Full text API</option><option value="browser">Website access</option></select></Field></>}</div><button className="button outline compact" disabled={busy} onClick={()=>void create()}>{busy?<Spinner/>:<Link2 size={15}/>}Connect {name(provider)}</button></div>}
  {error&&<ErrorNotice message={error} onClose={()=>setError('')}/>}
  {disconnected&&cards.length>0&&<p className="connection-stale" role="status">Connection updates paused. Last known state is shown; retrying.</p>}
  {cards.map(card=><ConnectionActionCard key={card.id} card={card} client={client} onUpdate={update} onNavigate={onNavigate} agentBackend={agentBackend} agentModel={agentModel} selectedProfile={selectedProfile} onSelectProfile={onSelectProfile}/>)}
  {(providers.length>0||sourceQuotas.length>0)&&<ProviderAccounts providers={providers} sourceQuotas={sourceQuotas} onRefresh={()=>void refresh()}/>}
 </section>;
}

export function ConnectionActionCard({card,client,onUpdate,onNavigate,agentBackend='codex',agentModel,selectedProfile,onSelectProfile}:{card:ConnectionCard;client:OreClient;onUpdate:(value:ConnectionCard)=>void;onNavigate:(path:string)=>void;agentBackend?:string;agentModel?:string;selectedProfile?:string;onSelectProfile?:(id:string)=>void}){
 const [loginCode,setLoginCode]=useState('');
 const [field,setField]=useState(''),[value,setValue]=useState(''),[keyLabel,setKeyLabel]=useState('primary'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const fields=(card.credential_fields??[]).filter(item=>['username','password','api_key','email','client_id','token','insttoken'].includes(item));
 const selected=fields.includes(field)?field:fields[0]??'';
 const pooledKey=card.kind==='source'&&card.provider!=='pubmed'&&selected==='api_key'&&card.credential_pool_allowed===true;
 const validKeyLabel=/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/.test(keyLabel.trim());
 const verification=officialLogin(card.verification_url);
 useEffect(()=>{setValue('');setLoginCode('');setError('');},[card.id,card.status]);
 async function action(command:string){setBusy(true);setError('');try{onUpdate(await client.connectionAction(card,command,crypto.randomUUID(),command==='request_agent'?{agent_backend:agentBackend,...(agentModel?{agent_model:agentModel}:{})}:{}));}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}
 async function saveSecret(){if(!selected||!value||(pooledKey&&!validKeyLabel))return;const secret=value;setValue('');setBusy(true);setError('');try{onUpdate(await client.connectionSecret(card,selected,secret,crypto.randomUUID(),pooledKey?{credential_id:keyLabel.trim()}:{}));}catch{setError('The credential could not be saved. Check connection status and enter it again.');}finally{setBusy(false);}}
 async function finishLogin(){if(!loginCode)return;const code=loginCode;setLoginCode('');setBusy(true);setError('');try{onUpdate(await client.connectionLoginCode(card,code));}catch{setError('The authorization code was not accepted. Check login status and try a fresh code.');}finally{setBusy(false);}}
 const handoff=card.handoff_id?'/handoffs/'+encodeURIComponent(card.handoff_id):card.handoff_href?.startsWith('/handoffs/')?card.handoff_href:undefined;
 return <article className="connection-action-card" aria-label={name(card.provider)+' connection'} data-connection-id={card.id}>
  <header><div><KeyRound size={17}/><strong>{name(card.provider)}</strong>{card.kind==='source'&&<small>{label(card.operation)}</small>}</div><Status value={card.status}/></header>
  {(card.message||messages[card.message_code??''])&&<p>{card.message??messages[card.message_code??'']}</p>}
  {['pending','approval_pending'].includes(card.status)&&<p>Approval is pending. This connection is not ready for collection.</p>}
  {verification&&<div className="official-login"><a href={verification} target="_blank" rel="noopener noreferrer" className="button outline compact">Continue on {name(card.provider)}<ExternalLink size={14}/></a>{card.user_code&&<div><span>One-time code</span><code>{card.user_code}</code></div>}{card.expires_at&&<small>Expires {quotaDate(card.expires_at)}</small>}</div>}
  {card.login_code_required&&<form className="connection-login-code" onSubmit={event=>{event.preventDefault();void finishLogin();}}><Field label={name(card.provider)+' authorization code'}><input type="password" autoComplete="off" spellCheck={false} value={loginCode} onChange={event=>setLoginCode(event.target.value)}/></Field><button className="button outline compact" disabled={busy||!loginCode}>Complete official login</button></form>}
  {!!fields.length&&<details className="connection-secret"><summary><ShieldCheck size={14}/>Enter a credential securely</summary><p>Sent directly to the server’s protected store. It is not added to chat history.</p><form onSubmit={event=>{event.preventDefault();void saveSecret();}}><Field label={'Credential field for '+name(card.provider)}><select value={selected} onChange={event=>{setField(event.target.value);setValue('');}}>{fields.map(item=><option value={item} key={item}>{label(item)}{card.configured_fields?.includes(item)?' · saved':''}</option>)}</select></Field>{pooledKey&&<Field label={'Key label for '+name(card.provider)}><input value={keyLabel} maxLength={64} list={'key-labels-'+card.id} autoComplete="off" onChange={event=>setKeyLabel(event.target.value)}/><datalist id={'key-labels-'+card.id}>{(card.credential_pool??[]).map(item=><option key={item.id} value={item.id}/>)}</datalist></Field>}<Field label={name(card.provider)+' '+label(selected)}><input type="password" autoComplete="off" spellCheck={false} value={value} onChange={event=>setValue(event.target.value)}/></Field><button className="button outline compact" disabled={busy||!value||(pooledKey&&!validKeyLabel)}>Save credential</button></form>{pooledKey&&<p>Choose a label to add or replace a saved key. Keys share the provider’s allowance; adding keys does not increase that allowance.</p>}</details>}
  {error&&<ErrorNotice message={error}/>}
  {card.kind==='source'&&card.access_profile_ref&&onSelectProfile&&card.access_profile_ref!==selectedProfile&&<p className="connection-use-profile">Profile: {card.access_profile_ref} <button className="button outline compact" onClick={()=>onSelectProfile(card.access_profile_ref!)}>Use for this chat</button></p>}
  <div className="connection-actions">{(card.actions??[]).filter(item=>item in captions).map(item=><button className="button outline compact" key={item} disabled={busy||(item==='request_agent'&&!['codex','claude_code'].includes(agentBackend))} onClick={()=>void action(item)}>{['refresh','verify'].includes(item)?<RefreshCw size={14}/>:null}{item==='request_agent'?'Ask '+name(agentBackend)+' to assist':captions[item]}</button>)}{handoff&&<button className="button primary compact" onClick={()=>onNavigate(handoff)}>Open browser step</button>}{busy&&<Spinner/>}</div>
  {card.actions?.includes('request_agent')&&!['codex','claude_code'].includes(agentBackend)&&<p>Browser setup assistance uses Codex or Claude Code. You can still open the provider and save an API key here.</p>}
  {card.kind==='source'&&<ConnectionEnrollment client={client} card={card}/>}
  {card.observed_at&&<small className="connection-observed">Updated {date(card.observed_at)}</small>}
 </article>;
}

export function ProviderAccounts({providers,sourceQuotas=[],onRefresh}:{providers:ProviderStatus[];sourceQuotas?:SourceQuota[];onRefresh:()=>void}){
 return <details className="provider-accounts"><summary>Model accounts and API quota</summary><p>Provider allowance is separate from this request’s time and token budgets.</p>{providers.map(provider=>{const quota=provider.quota;const stale=quota?.stale||quota?.status==='stale';const windows=quota?.windows??[];return <section key={provider.provider} aria-label={name(provider.provider)+' account quota'}><header><strong>{name(provider.provider)}</strong><Status value={provider.auth?.status??'unknown'}/></header>{provider.auth?.plan_type&&<p>{provider.auth.plan_type}{provider.auth.mode?' · '+label(provider.auth.mode):''}</p>}{stale&&<p role="status">Last known quota · stale</p>}{windows.map(window=><div className="quota-window" key={window.id}><span>{label(window.id)}{window.window_minutes?' · '+window.window_minutes+' min':''}</span><strong>{typeof window.remaining_percent==='number'?window.remaining_percent+'% remaining':typeof window.used_percent==='number'?window.used_percent+'% used':'Unknown'}</strong>{window.resets_at&&<small>Resets {quotaDate(window.resets_at)}</small>}</div>)}{!windows.length&&<p>{quota?.status==='unsupported'?'The provider does not expose quota through this connection.':'Quota is not available yet.'}</p>}{quota?.ordinary_usage_allowed===false&&<p>Provider usage is currently restricted.</p>}{quota?.observed_at&&<small>Observed {quotaDate(quota.observed_at)}</small>}</section>;})}{sourceQuotas.map(quota=><section key={(quota.source??quota.access_profile_ref??'source')+':'+(quota.credential_id??'shared')+':'+quota.quota_group} aria-label={name(quota.source??'Source')+' API quota'}><header><strong>{name(quota.source??'Source')} API</strong><Status value={quota.status}/></header><p>{typeof quota.remaining==='number'?quota.remaining.toLocaleString()+' requests remaining':'Remaining requests unknown'}{typeof quota.limit==='number'?' / '+quota.limit.toLocaleString():''}</p>{quota.access_profile_ref&&<small>Profile: {quota.access_profile_ref}</small>}{quota.resets_at&&<p>Resets {quotaDate(quota.resets_at)}</p>}{quota.observed_at&&<small>Observed {quotaDate(quota.observed_at)}</small>}</section>)}<button className="button subtle compact" onClick={onRefresh}><RefreshCw size={14}/>Refresh account status</button></details>;
}
