import { useEffect, useState } from 'react';
import { ArrowUpRight, CircleHelp, KeyRound, Layers3, Link2, Plus, Save, ShieldCheck } from 'lucide-react';
import { OreClient } from '@ore/sdk';
import type { AccessProfile, JsonObject, Source } from '@ore/sdk';
import { ErrorNotice, Field, JsonView, Spinner, Status } from './Common';
import { errorMessage, label, record, text } from '../lib/format';
export default function ConnectionsView({client,profiles,sources,onChanged}:{client:OreClient;profiles:AccessProfile[];sources:Source[];onChanged:()=>void}){
 const [auth,setAuth]=useState<JsonObject|null>(null);const [original,setOriginal]=useState<JsonObject>({});const [error,setError]=useState('');const [editing,setEditing]=useState(false);const [busy,setBusy]=useState(false);const [id,setId]=useState('');const [name,setName]=useState('');const [network,setNetwork]=useState('institution');const [origins,setOrigins]=useState('');const [secretRefs,setSecretRefs]=useState('');
 useEffect(()=>{client.authStatus().then(setAuth).catch(cause=>setError(errorMessage(cause)));},[client]);
 function edit(profile?:AccessProfile){setOriginal(profile??{});setId(profile?.id??'');setName(profile?.name??'');setNetwork(profile?.network??'institution');setOrigins((profile?.origins??[]).join('\n'));setSecretRefs(Object.entries(record(profile?.sources)).flatMap(([source,settings])=>Object.entries(record(settings)).filter(([key])=>key.endsWith('_ref')).map(([key,value])=>`${source}.${key}=${value}`)).join('\n'));setEditing(true);}
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const refs:Record<string,string>={};const sourceConfig:Record<string,Record<string,string>>=Object.fromEntries(Object.entries(record(original.sources)).map(([source,settings])=>[source,Object.fromEntries(Object.entries(record(settings)).filter(([key])=>!key.endsWith('_ref')))])) as Record<string,Record<string,string>>;for(const line of secretRefs.split('\n').map(v=>v.trim()).filter(Boolean)){const at=line.indexOf('=');if(at<1||!line.slice(at+1).trim())throw new Error('Use name=reference for each secret reference.');const key=line.slice(0,at).trim();const value=line.slice(at+1).trim();const dot=key.indexOf('.');if(dot<1||!key.endsWith('_ref'))throw new Error('Use source.field_ref=reference, for example scopus.api_key_ref=env:SCOPUS_API_KEY.');const source=key.slice(0,dot);sourceConfig[source]??={};sourceConfig[source]![key.slice(dot+1)]=value;refs[key]=value;}await client.saveAccessProfile({...original,id:id.trim(),name:name.trim()||id.trim(),network,origins:origins.split(/[\n,]/).map(v=>v.trim()).filter(Boolean),secret_refs:refs,sources:sourceConfig});setEditing(false);onChanged();}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}
 const account=record(auth?.account);const codex=record(auth?.codex);
 return <section className="page"><header className="page-heading"><div><div className="eyebrow">YOUR EXECUTION ENVIRONMENT</div><h1>Connections & access</h1><p>Connect the agent, search sources and approved institution access.</p></div><button className="button primary" onClick={()=>edit()}><Plus size={16}/>Access profile</button></header>{error&&<ErrorNotice message={error} onClose={()=>setError('')}/>}
 <div className="connection-grid"><section className="panel agent-connection"><div className="panel-heading"><h3><Link2 size={17}/>Codex backend</h3><Status value={text(auth?.status??codex.status,auth?.codex_installed===false?'not_local':auth?'available':'checking')}/></div><h3>Use your existing Codex sign-in</h3><p>A local or registered host runner uses the installed Codex agent. Model inference uses its connected account; no local model server is required.</p><div className="key-values"><div><span>Authentication</span><strong>{text(auth?.auth_mode??codex.auth_mode??account.type,'Managed by Codex')}</strong></div><div><span>Model availability</span><strong>Discovered from the backend</strong></div></div><div className="info-callout"><CircleHelp size={16}/><span>Sign in on the ORE server using <code>codex login</code>. ORE does not need a copy of your Codex tokens.</span></div>{auth&&<details><summary>Connection details</summary><JsonView value={auth}/></details>}</section>
 <section className="panel"><div className="panel-heading"><h3><ShieldCheck size={17}/>Access profiles <span>{profiles.length}</span></h3></div>{profiles.length?profiles.map(profile=><button className="profile-row" key={profile.id} onClick={()=>edit(profile)}><KeyRound size={18}/><span><strong>{profile.name||profile.id}</strong><small>{label(profile.network||'public')} · {(profile.origins??[]).length} origins</small></span><ArrowUpRight size={15}/></button>):<div className="compact-empty"><KeyRound size={23}/><h3>Public access is ready</h3><p>Add an institution or approved proxy profile when you need subscription access.</p></div>}<p className="panel-note">Profiles describe the server's access path. They do not create subscription entitlements or change its network.</p></section></div>
 {editing&&<form className="panel profile-form" onSubmit={save}><div className="panel-heading"><h3>Configure access profile</h3><button type="button" className="button subtle compact" onClick={()=>setEditing(false)}>Cancel</button></div><div className="form-grid three"><Field label="Profile ID"><input required pattern="[A-Za-z0-9._:-]+" value={id} onChange={e=>setId(e.target.value)} placeholder="institution-library"/></Field><Field label="Display name"><input value={name} onChange={e=>setName(e.target.value)} placeholder="University library"/></Field><Field label="Network"><select value={network} onChange={e=>setNetwork(e.target.value)}><option value="public">Public</option><option value="institution">Institution network</option><option value="approved_proxy">Approved proxy</option></select></Field></div><div className="form-grid"><Field label="Allowed origins" hint="One https:// origin per line, including approved attachment hosts."><textarea rows={4} value={origins} onChange={e=>setOrigins(e.target.value)} placeholder="https://journal.example.org"/></Field><Field label="Secret references" hint="Source references only, for example scopus.api_key_ref=env:SCOPUS_API_KEY. Never paste passwords, tokens or cookies here."><textarea rows={4} value={secretRefs} onChange={e=>setSecretRefs(e.target.value)} placeholder="scopus.api_key_ref=env:SCOPUS_API_KEY"/></Field></div><button className="button primary" disabled={busy}>{busy?<Spinner/>:<Save size={16}/>}Save access profile</button></form>}
 <section className="panel source-panel"><div className="panel-heading"><h3><Layers3 size={17}/>Search & retrieval sources</h3><span className="muted small">{sources.length} adapters</span></div><div className="source-grid">{sources.map(source=><article key={source.id}><div className="source-top"><Layers3 size={18}/><Status value={source.status??(source.enabled===false?'disabled':'available')}/></div><h3>{source.name||label(source.id)}</h3><p>{text(source.description,'Search metadata and discover available retrieval paths.')}</p><small>{text(source.kind??source.type,'Source adapter')}</small></article>)}</div></section></section>;
}
