import {useCallback,useEffect,useState} from 'react';
import {Folder,FolderPlus,GitBranch,MessageCircle,MoreHorizontal,Pencil,Trash2} from 'lucide-react';
import type {ConversationFolder,ConversationSummary,OreClient} from '@ore/sdk';
import {ErrorNotice} from './Common';
import {errorMessage} from '../lib/format';

export default function ConversationLibrary({client,conversations,selected,search,onNavigate,onChanged}:{client:OreClient;conversations:ConversationSummary[];selected:string;search:string;onNavigate:(path:string)=>void;onChanged:()=>void}){
 const [folders,setFolders]=useState<ConversationFolder[]>([]),[editing,setEditing]=useState<string|null>(null),[title,setTitle]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(()=>client.conversationFolders().then(setFolders),[client]);
 useEffect(()=>{void load().catch(()=>undefined);},[load,conversations]);
 const filtered=conversations.filter(item=>item.title.toLowerCase().includes(search.toLowerCase()));
 async function saveFolder(){if(!title.trim())return;setBusy(true);setError('');try{if(editing==='new')await client.createConversationFolder(title.trim());else if(editing)await client.updateConversationFolder(editing,title.trim());setEditing(null);setTitle('');await load();onChanged();}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}
 async function removeFolder(id:string){setBusy(true);setError('');try{await client.deleteConversationFolder(id);await load();onChanged();}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}
 async function updateConversation(id:string,patch:{title?:string;folder_id?:string|null}){setError('');await client.updateConversation(id,patch).then(()=>onChanged()).catch(cause=>setError(errorMessage(cause)));}
 function row(item:ConversationSummary){return <ConversationRow key={item.id} item={item} selected={selected===item.id} folders={folders} onOpen={()=>onNavigate('/chat/'+encodeURIComponent(item.id))} onUpdate={patch=>updateConversation(item.id,patch)}/>;}
 const loose=filtered.filter(item=>!item.folder_id||!folders.some(folder=>folder.id===item.folder_id));
 return <div className="conversation-sidebar"><div className="conversation-library-heading"><div className="nav-caption">CONVERSATIONS</div><button className="icon-button" aria-label="Create purpose folder" onClick={()=>{setEditing('new');setTitle('');}}><FolderPlus size={15}/></button></div>{error&&<ErrorNotice message={error} onClose={()=>setError('')}/>}{editing&&<form className="folder-form" onSubmit={event=>{event.preventDefault();void saveFolder();}}><label htmlFor="folder-title">{editing==='new'?'New purpose folder':'Rename folder'}</label><input id="folder-title" autoFocus value={title} onChange={event=>setTitle(event.target.value)} placeholder="e.g. Cardiology review" maxLength={200}/><div><button type="submit" disabled={busy||!title.trim()}>Save folder</button><button type="button" onClick={()=>setEditing(null)}>Cancel</button></div></form>}{folders.map(folder=><details className="conversation-folder" key={folder.id} open><summary><Folder size={15}/><span>{folder.title}</span><small>{filtered.filter(item=>item.folder_id===folder.id).length}</small></summary><div className="folder-actions"><button title={'Rename '+folder.title} aria-label={'Rename folder '+folder.title} onClick={()=>{setEditing(folder.id);setTitle(folder.title);}}><Pencil size={12}/>Rename</button><button title="Conversations are kept outside the folder" aria-label={'Remove folder '+folder.title} disabled={busy} onClick={()=>void removeFolder(folder.id)}><Trash2 size={12}/>Remove folder</button></div>{filtered.filter(item=>item.folder_id===folder.id).map(row)}</details>)}{loose.length>0&&folders.length>0&&<div className="nav-caption">UNFILED</div>}{loose.map(row)}{!conversations.length&&<p>Your conversations will appear here.</p>}{conversations.length>0&&!filtered.length&&<p>No matching conversations.</p>}</div>;
}
function ConversationRow({item,selected,folders,onOpen,onUpdate}:{item:ConversationSummary;selected:boolean;folders:ConversationFolder[];onOpen:()=>void;onUpdate:(patch:{title?:string;folder_id?:string|null})=>Promise<void>}){
 const [renaming,setRenaming]=useState(false),[title,setTitle]=useState(item.title),[busy,setBusy]=useState(false);
 async function save(){setBusy(true);try{await onUpdate({title:title.trim()});setRenaming(false);}finally{setBusy(false);}}
 return <div className={'conversation-library-row '+(selected?'selected':'')}><button className={selected?'active':''} title={item.title} onClick={onOpen}>{item.branched_from?<GitBranch size={15}/>:<MessageCircle size={15}/>}<span>{item.title||'New conversation'}</span>{['planning','running'].includes(item.status)&&<i className="conversation-running"/>}</button><details className="conversation-row-menu"><summary aria-label={'Manage conversation '+item.title}><MoreHorizontal size={15}/></summary><div>{renaming?<form onSubmit={event=>{event.preventDefault();void save();}}><label>Conversation title<input value={title} onChange={event=>setTitle(event.target.value)} maxLength={200}/></label><button disabled={busy||!title.trim()}>Save title</button></form>:<button onClick={()=>{setTitle(item.title);setRenaming(true);}}>Rename conversation</button>}<label>Move to folder<select aria-label={'Folder for '+item.title} value={item.folder_id??''} onChange={event=>void onUpdate({folder_id:event.target.value||null})}><option value="">Unfiled</option>{folders.map(folder=><option key={folder.id} value={folder.id}>{folder.title}</option>)}</select></label>{item.branched_from&&<small>Branched conversation</small>}</div></details></div>;
}
