import { useState } from 'react';
import { ArrowLeft, ArrowUpRight, CheckCheck, ChevronDown, Download, FileCheck2, FileText, Layers3, Pause, Play, RefreshCw, Save, Search, ShieldCheck } from 'lucide-react';
import type { Artifact, Job, OreEvent, Resource } from '@ore/sdk';
import { Empty, ExternalLink, JsonView, Spinner, Status } from './Common';
import { bytes, date, instructions, jobName, label, listText, record, text } from '../lib/format';
interface Props {job:Job;resources:Resource[];artifacts:Artifact[];events:OreEvent[];streamState:string;busy:boolean;onBack:()=>void;onAction:(action:'run'|'pause'|'resume'|'refresh'|'audit')=>void;onRevise:(instructions:string)=>Promise<void>;onExport:()=>void;onDownload:(artifact:Artifact)=>void;}
function artifactVerified(artifact:Artifact){return ['verified','succeeded','complete'].includes(artifact.status??'');}
function titleOf(item:Resource){return text(item.title??record(item.metadata).title,'Untitled resource');}
export default function JobDetail({job,resources,artifacts,events,streamState,busy,onBack,onAction,onRevise,onExport,onDownload}:Props){
 const [tab,setTab]=useState('resources');const [search,setSearch]=useState('');const [editing,setEditing]=useState(false);const [draft,setDraft]=useState('');const [revising,setRevising]=useState(false);
 const mission=record(job.mission);const main=artifacts.filter(a=>a.role==='main_pdf'&&artifactVerified(a));const supplements=artifacts.filter(a=>a.role==='supplement');const suppVerified=supplements.filter(artifactVerified).length;const verified=artifacts.filter(artifactVerified).length;const status=job.status??'queued';const running=['running','discovering','collecting','auditing'].includes(status);
 const filteredResources=resources.filter(resource=>`${titleOf(resource)} ${resource.doi??''} ${resource.source??''}`.toLowerCase().includes(search.toLowerCase()));const filteredArtifacts=artifacts.filter(artifact=>`${artifact.filename??artifact.name??artifact.id} ${artifact.role??''} ${artifact.status??''}`.toLowerCase().includes(search.toLowerCase()));
 const report=job.audit??job.coverage??job.report;
 async function revise(){setRevising(true);try{await onRevise(draft);setEditing(false);}catch{/* parent shows the API error; keep the draft open */}finally{setRevising(false);}}
 return <section className="page detail-page"><button className="back-link" onClick={onBack}><ArrowLeft size={14}/>All missions</button><header className="page-heading"><div><div className="eyebrow">MISSION / {job.id.slice(0,12)}</div><h1>{jobName(job)}</h1><div className="mission-subtitle"><Status value={status}/><span>Created {date(job.created_at)}</span><span>Revision {text(job.revision??job.mission_revision,'1')}</span></div></div><div className="action-group"><button className="button subtle" onClick={onExport} disabled={busy}><Download size={16}/>Export</button>{running?<button className="button outline" onClick={()=>onAction('pause')} disabled={busy}><Pause size={16}/>Pause</button>:<button className="button primary" onClick={()=>onAction(['queued','created','draft'].includes(status)?'run':'resume')} disabled={busy}>{busy?<Spinner/>:<Play size={16}/>} {['queued','created','draft'].includes(status)?'Run mission':'Resume'}</button>}</div></header>
 <div className="metrics-grid"><Metric label="Discovered resources" value={resources.length} icon={<Layers3 size={19}/>} caption="Candidates in this mission"/><Metric label="Verified main PDFs" value={new Set(main.map(a=>a.resource_id??a.id)).size} icon={<FileCheck2 size={19}/>} caption="Unique resources with a main PDF"/><Metric label="Supplements retrieved" value={suppVerified} icon={<FileText size={19}/>} caption={`${supplements.length} known supplementary files`}/><Metric label="Verified artifacts" value={verified} icon={<CheckCheck size={19}/>} caption={`${artifacts.length-verified} not yet verified`}/></div>
 <div className="mission-summary panel"><div><div className="panel-heading"><h3>Mission brief</h3><button className="text-button" onClick={()=>{setDraft(instructions(job));setEditing(!editing);}}>{editing?'Cancel':'Revise instructions'}</button></div>{editing?<div className="revision-form"><textarea rows={4} value={draft} onChange={e=>setDraft(e.target.value)} aria-label="Revised instructions"/><button className="button primary compact" onClick={()=>void revise()} disabled={revising||!draft.trim()}>{revising?<Spinner/>:<Save size={14}/>}Save revision</button></div>:<p className="brief-text">{instructions(job)}</p>}<div className="brief-tags"><span><Layers3 size={12}/>{listText(mission.sources)}</span><span><FileText size={12}/>{listText(mission.artifact_roles)}</span>{mission.query? <span><Search size={12}/>{text(mission.query)}</span>:null}</div></div><aside><div><span>Access</span><strong>{text(mission.access_profile_ref,'Public')}</strong></div><div><span>Routing</span><strong>{label(text(record(mission.routing).mode,'auto'))}</strong></div><div><span>Agent limit</span><strong>{text(record(mission.limits).max_agent_workers,'—')}</strong></div><div className="summary-actions"><button className="text-button" onClick={()=>onAction('audit')} disabled={busy}><ShieldCheck size={14}/>Audit coverage</button><button className="text-button" onClick={()=>onAction('refresh')} disabled={busy||running}><RefreshCw size={13}/>New observation</button></div></aside></div>
 <div className="detail-columns"><section className="panel results-panel"><div className="results-header"><div className="tabs"><button className={tab==='resources'?'active':''} onClick={()=>{setTab('resources');setSearch('');}}>Resources <span>{resources.length}</span></button><button className={tab==='artifacts'?'active':''} onClick={()=>{setTab('artifacts');setSearch('');}}>Artifacts <span>{artifacts.length}</span></button><button className={tab==='coverage'?'active':''} onClick={()=>setTab('coverage')}>Coverage</button></div>{tab!=='coverage'&&<div className="search-field"><Search size={14}/><input placeholder="Filter results…" aria-label="Filter results" value={search} onChange={e=>setSearch(e.target.value)}/></div>}</div>
 {tab==='resources'&&(filteredResources.length?<div className="table-scroll"><table><thead><tr><th>Resource</th><th>Source</th><th>State</th></tr></thead><tbody>{filteredResources.map(resource=><tr key={resource.id}><td><div className="resource-title"><ExternalLink href={resource.url??resource.canonical_url}>{titleOf(resource)}</ExternalLink></div><div className="resource-meta">{resource.doi?<span>{resource.doi}</span>:<span>{resource.id.slice(0,16)}</span>}{resource.year&&<span>{resource.year}</span>}</div></td><td><span className="source-tag">{text(resource.source??resource.source_id)}</span></td><td><Status value={resource.status??String(resource.classification??resource.eligibility??'discovered')}/></td></tr>)}</tbody></table></div>:<Empty icon={<Search size={24}/>} title={search?'No matching resources':'Discovery starts here'}>{search?'Try a different title, DOI or source.':'Run this mission to discover source records and their retrieval paths.'}</Empty>)}
 {tab==='artifacts'&&(filteredArtifacts.length?<div className="table-scroll"><table><thead><tr><th>File</th><th>Role / size</th><th>Verification</th></tr></thead><tbody>{filteredArtifacts.map(artifact=><tr key={artifact.id}><td><div className="resource-title"><ExternalLink href={artifact.url??artifact.source_url}>{text(artifact.filename??artifact.name,artifact.id)}</ExternalLink></div><div className="resource-meta">{artifact.sha256?<span title={artifact.sha256}>SHA-256 {artifact.sha256.slice(0,16)}…</span>:<span>Hash pending</span>}</div></td><td><span>{label(artifact.role??'file')}</span><small className="block muted">{bytes(artifact.bytes??artifact.size_bytes)}</small></td><td><Status value={artifact.status??'pending'}/>{artifact.sha256&&<button className="artifact-download text-button" onClick={()=>onDownload(artifact)} disabled={busy}><Download size={12}/>Download</button>}</td></tr>)}</tbody></table></div>:<Empty icon={<FileText size={26}/>} title={search?'No matching artifacts':'Files appear after retrieval'}>Main PDFs and supplementary files retain their source, role and verification status.</Empty>)}
 {tab==='coverage'&&<div className="coverage-view"><div className="info-callout"><ShieldCheck size={18}/><span>Verified files, known supplementary links and unresolved records are reported separately. An absent link is not proof that no supplement exists.</span></div>{report?<JsonView value={report}/>:<Empty icon={<ShieldCheck size={25}/>} title="Coverage report is not available yet" action={<button className="button outline" onClick={()=>onAction('audit')} disabled={busy}>Run audit</button>}>Run an audit to reconcile the current inventory and artifact states.</Empty>}</div>}
 </section><aside className="panel activity-panel"><div className="panel-heading"><h3>Live activity</h3><span className={`stream-label ${streamState==='live'?'live':''}`}><i/>{streamState}</span></div><div className="activity-list">{events.length?[...events].reverse().map((event,index)=>{const envelope=record(event.data);const payload=record(envelope.payload??envelope);const kind=text(envelope.type,event.event);return <div className="activity-item" key={`${event.id??envelope.id??index}-${index}`}><div className="activity-node"/><div><div className="activity-meta"><strong>{label(kind)}</strong><time>{date(envelope.created_at??payload.created_at)}</time></div><p>{text(payload.message??payload.summary??payload.reason??payload.status,kind==='message'?'Agent update':label(kind))}</p>{Object.keys(payload).length>0&&<details><summary>Details <ChevronDown size={11}/></summary><JsonView value={payload}/></details>}</div></div>;}):<Empty icon={<ArrowUpRight size={21}/>} title="Ready for the first step">Agent decisions and tool results appear here as the mission runs.</Empty>}</div><footer className="activity-footer">Showing the latest {events.length} events</footer></aside></div>
 </section>;
}
function Metric({label:caption,value,caption:detail,icon}:{label:string;value:number;caption:string;icon:React.ReactNode}){return <article className="metric"><div><span>{caption}</span>{icon}</div><strong>{value.toLocaleString()}</strong><small>{detail}</small></article>;}
