import { useState } from 'react';
import { ArrowRight, Check, Layers3, X } from 'lucide-react';
import type { AccessProfile, JsonObject, Model, Rune, Source } from '@ore/sdk';
import { Field, Spinner } from './Common';
import { errorMessage, label, record, text } from '../lib/format';
interface Props {sources:Source[];models:Model[];profiles:AccessProfile[];runes?:Rune[];onClose:()=>void;onCreate:(mission:JsonObject,start:boolean)=>Promise<void>;}
export default function MissionForm({sources,models,profiles,runes=[],onClose,onCreate}:Props){
  const currentYear=new Date().getFullYear();
  const [name,setName]=useState('');const [instructions,setInstructions]=useState('');const [query,setQuery]=useState('');
  const [selected,setSelected]=useState<string[]>(sources.slice(0,2).map(s=>s.id));const [journals,setJournals]=useState('');const [urls,setUrls]=useState('');const [runeId,setRuneId]=useState('');const [allowedOrigins,setAllowedOrigins]=useState('');
  const [from,setFrom]=useState(currentYear-20);const [to,setTo]=useState(currentYear-1);const [roles,setRoles]=useState(['main_pdf','supplement']);
  const [profile,setProfile]=useState('');const [routing,setRouting]=useState('auto');const [model,setModel]=useState(models[0]?.model ?? models[0]?.id ?? '');
  const [effort,setEffort]=useState('');const [workers,setWorkers]=useState(2);const [start,setStart]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const selectedModel=models.find(m=>(m.model??m.id)===model);const efforts=(selectedModel?.supportedReasoningEfforts ?? selectedModel?.supported_reasoning_efforts ?? []) as unknown[];
  const toggle=(value:string,list:string[],set:(value:string[])=>void)=>set(list.includes(value)?list.filter(v=>v!==value):[...list,value]);
  async function submit(event:React.FormEvent){event.preventDefault();setError('');if(from>to){setError('The start year must be before the end year.');return;}if(!selected.length&&!urls.trim()){setError('Choose a search source or provide a starting URL.');return;}if(!roles.length){setError('Choose at least one artifact type.');return;}setBusy(true);try{
    await onCreate({name:name.trim()||'Untitled mission',instructions:instructions.trim(),query:query.trim(),sources:selected,urls:urls.split(/[\n,]/).map(v=>v.trim()).filter(Boolean),allowed_origins:allowedOrigins.split(/[\n,]/).map(v=>v.trim()).filter(Boolean),...(runeId?{rune_id:runeId}:{}),journals:journals.split(/[\n,]/).map(v=>v.trim()).filter(Boolean),publication_window:{basis:'publication_date',from:`${from}-01-01`,until_exclusive:`${to+1}-01-01`},artifact_roles:roles,...(profile?{access_profile_ref:profile}:{}),routing:{mode:routing,...(routing==='fixed'?{model,...(effort?{effort}:{})}:{})},limits:{max_agent_workers:workers}},start);
  }catch(cause){setError(errorMessage(cause));setBusy(false);}}
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose();}}><section className="mission-modal" role="dialog" aria-modal="true" aria-labelledby="mission-title"><header className="modal-header"><div><div className="eyebrow">DEFINE THE MISSION</div><h2 id="mission-title">What should ORE retrieve?</h2><p>A clear goal. A defined scope. Evidence for every result.</p></div><button className="icon-button" aria-label="Close mission form" onClick={onClose} disabled={busy}><X/></button></header>
  <form onSubmit={submit}><div className="modal-body"><Field label="Mission name"><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Transplantation · 20-year archive" maxLength={160}/></Field>
  <Field label="Instructions" hint="Describe the goal, inclusion criteria and any site-specific sequence the agent should follow."><textarea required rows={4} value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Find original research articles published in the selected journals. Retrieve the published main PDF and all supplementary files. Record unavailable files and uncertain article types."/></Field>
  <div className="form-grid"><Field label="Search query" hint="Source adapters use this query to discover candidate records."><input value={query} onChange={e=>setQuery(e.target.value)} placeholder='e.g. "graft versus host disease"'/></Field><Field label="Journals or ISSNs" hint="Comma-separated names or ISSNs; leave blank for a topic search."><input value={journals} onChange={e=>setJournals(e.target.value)} placeholder="Blood, 0006-4971"/></Field></div>
  <div className="form-section"><div className="field-label">Search sources <span>{selected.length} selected</span></div><div className="source-options">{sources.length?sources.map(source=><button type="button" key={source.id} className={`source-option ${selected.includes(source.id)?'selected':''}`} onClick={()=>toggle(source.id,selected,setSelected)}><Layers3 size={16}/><span>{source.name||label(source.id)}</span>{selected.includes(source.id)&&<Check size={15}/>}</button>):<p className="muted">No search adapters are available. You can still start from a direct URL.</p>}</div></div>
  <div className="form-grid"><Field label="Starting URLs" hint="Optional archive or article URLs, one per line. Direct URLs also work without a search source."><textarea rows={2} value={urls} onChange={e=>setUrls(e.target.value)} placeholder="https://journal.example.org/archive"/></Field><Field label="Rune protocol" hint="Reuse a site-specific procedure and its validation contract."><select value={runeId} onChange={e=>setRuneId(e.target.value)}><option value="">Use mission instructions</option>{runes.map(rune=><option key={rune.id} value={rune.id}>{rune.name||rune.id}</option>)}</select></Field></div><div className="form-grid three"><Field label="From year"><input type="number" min={1600} max={currentYear} value={from} onChange={e=>setFrom(Number(e.target.value))} required/></Field><Field label="Through year"><input type="number" min={1600} max={currentYear} value={to} onChange={e=>setTo(Number(e.target.value))} required/></Field><Field label="Parallel agents"><input type="number" min={1} max={8} value={workers} onChange={e=>setWorkers(Number(e.target.value))} required/></Field></div>
  <div className="form-grid"><div><div className="field-label">Artifacts to retrieve</div><div className="checkbox-row"><label><input type="checkbox" checked={roles.includes('main_pdf')} onChange={()=>toggle('main_pdf',roles,setRoles)}/> Main PDF</label><label><input type="checkbox" checked={roles.includes('supplement')} onChange={()=>toggle('supplement',roles,setRoles)}/> Supplementary files</label></div></div><Field label="Access profile"><select value={profile} onChange={e=>setProfile(e.target.value)}><option value="">Public access</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name||p.id}</option>)}</select></Field></div>
  <details className="advanced"><summary>Agent & reasoning settings</summary><Field label="Restrict retrieval origins" hint="Optional comma-separated origins. Include approved CDN and attachment hosts when restricting a mission."><input value={allowedOrigins} onChange={e=>setAllowedOrigins(e.target.value)} placeholder="https://journal.example.org, https://files.example.org"/></Field><div className="form-grid three"><Field label="Routing"><select value={routing} onChange={e=>setRouting(e.target.value)}><option value="auto">Automatic</option><option value="fixed">Fixed model</option></select></Field><Field label="Model"><select value={model} disabled={routing==='auto'} onChange={e=>{setModel(e.target.value);setEffort('');}}><option value="">Codex default</option>{models.map(m=><option key={m.id} value={m.model??m.id}>{m.displayName||m.name||m.id}</option>)}</select></Field><Field label="Reasoning effort"><select value={effort} disabled={routing==='auto'} onChange={e=>setEffort(e.target.value)}><option value="">Model default</option>{efforts.map(v=>{const name=typeof v==='string'?v:text(record(v).reasoningEffort ?? record(v).reasoning_effort);return <option key={name} value={name}>{label(name)}</option>;})}</select></Field></div><p className="muted small">Available models and effort levels come from your connected backend. All agents share your account's usage limits.</p></details>
  {error&&<div className="form-error" role="alert">{error}</div>}</div><footer className="modal-footer"><label className="checkline"><input type="checkbox" checked={start} onChange={e=>setStart(e.target.checked)}/> Run after creating</label><div><button type="button" className="button subtle" onClick={onClose} disabled={busy}>Cancel</button><button className="button primary" disabled={busy}>{busy?<Spinner/>:start?<ArrowRight size={16}/>:<Check size={16}/>} {start?'Launch mission':'Create mission'}</button></div></footer></form></section></div>;
}
