import {useEffect,useState} from 'react';
import {OreClient} from '@ore/sdk';
import type {AccessProfile,Source} from '@ore/sdk';
import {ErrorNotice,Field,Spinner,Status} from './Common';
import {errorMessage,label,record,text} from '../lib/format';
export default function SourceWizard({client,profiles,onNavigate,onChanged}:{client:OreClient;profiles:AccessProfile[];onNavigate:(path:string)=>void;onChanged:()=>void}){
 const [profileId,setProfileId]=useState(()=>new URLSearchParams(location.search).get('profile')??'public'),[sources,setSources]=useState<Source[]>([]),[selected,setSelected]=useState(()=>new URLSearchParams(location.search).get('source')??''),[operation,setOperation]=useState(()=>new URLSearchParams(location.search).get('operation')??'search'),[key,setKey]=useState(''),[identifier,setIdentifier]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const profile=profiles.find(p=>p.id===profileId)??{id:profileId};
 async function load(){setSources(await client.sources(profileId));}
 useEffect(()=>{void client.sources(profileId).then(setSources).catch(e=>setError(errorMessage(e)));},[client,profileId,profiles]);
 async function setup(source:string,op:string){setBusy(true);setError('');try{const result=await client.sourceSetup(source,{operation:op,access_profile_ref:profileId});onChanged();onNavigate(result.href);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function storeKey(){setBusy(true);setError('');try{if(profileId==='public')throw new Error('Create or select your own access profile first.');const ref=`provider/${profileId}/${selected}/api_key`;await client.request(`/v1/secrets/${encodeURIComponent(ref)}`,{method:'PUT',body:JSON.stringify({value:key})});const config=record(profile.sources);await client.saveAccessProfile({...profile,sources:{...config,[selected]:{...record(config[selected]),api_key_ref:ref}}});setKey('');setNotice('Key stored. Availability remains unverified until the operation check succeeds.');onChanged();await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function check(){setBusy(true);setError('');try{const result=await client.sourceCheck(selected,{operation,access_profile_ref:profileId,...(identifier?{identifier}: {})});setNotice(`${label(text(result.state))} · ${text(result.scope)} · ${text(result.observed_at)}`);onChanged();await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <section className="panel source-panel"><div className="panel-heading"><h3>Choose the sources you need</h3><Status value="operator setup"/></div><p>Provider registration is optional. Use an existing account first. Only selected providers require setup; a pending API does not disable that provider's browser access.</p><Field label="Profile for source readiness"><select value={profileId} onChange={e=>{setProfileId(e.target.value);setSelected('');setKey('');}}><option value="public">Public</option>{profiles.filter(p=>p.id!=='public').map(p=><option key={p.id} value={p.id}>{p.name??p.id}</option>)}</select></Field>{error&&<ErrorNotice message={error}/>} {notice&&<p role="status" className="info-callout">{notice}</p>}
 <div className="source-grid">{sources.map(source=><article key={source.id}><h3>{source.name??label(source.id)}</h3><p>{text(source.description)}</p>{Object.entries(record(source.operation_readiness)).map(([op,value])=>{const state=record(value);return <div className="readiness-row" key={op}><span>{label(op)}</span><Status value={text(state.state,'unknown')}/><small>{text(state.observed_at,'No verified observation')}</small><div><button className="button subtle compact" disabled={busy} onClick={()=>{setSelected(source.id);setOperation(op);setKey('');setNotice('');}}>Configure / check</button>{['search','resolve','browser'].includes(op)&&<button className="button outline compact" disabled={busy} onClick={()=>void setup(source.id,op)}>Account setup</button>}</div></div>;})}</article>)}</div>
 {selected&&<div className="provider-key-form"><h3>{label(selected)} · {label(operation)}</h3><p>Existing users can store an issued key here. Account setup opens the provider in your executor browser; any new registration or terms remain your decision.</p><div className="form-grid"><Field label="Issued API key" hint="Stored only in the server's protected secret store. Never returned in source status."><input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)}/></Field>{operation==='resolve'&&<Field label="Identifier for bounded verification"><input value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="DOI or PMID"/></Field>}</div><div className="handoff-actions"><button className="button outline" disabled={busy||!key} onClick={()=>void storeKey()}>Store issued key</button><button className="button primary" disabled={busy||!['search','resolve'].includes(operation)} onClick={()=>void check()}>{busy?<Spinner/>:null}Verify this API operation</button><button className="button subtle" disabled={busy} onClick={()=>void setup(selected,operation)}>Existing account / registration</button></div><p className="muted small">For approval pending: open its request, mark it pending, then exclude that API operation from the mission. Browser or subscription access is not inferred from an issued key.</p></div>}
 </section>;
}
